l_braz_por:
 SETTINGS_PAGE_GRAPHICS:0 "Gráficos"
 SETTINGS_PAGE_GAME:0 "Jogo"
 SETTINGS_PAGE_SYSTEM:0 "Sistema"
 SETTINGS_PAGE_CONTROLS:0 "Controles"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE:0 "Interface"
 SETTINGS_PAGE_AUDIO:0 "Áudio"
 SETTINGS_CATEGORY_SCREEN:0 "Tela"
 SETTINGS_CATEGORY_QUALITY:0 "Qualidade"
 OPTION_EASY:0 "Fácil"
 OPTION_NORMAL:0 "Normal"
 OPTION_HARD:0 "Difícil"
 OPTION_NEVER:0 "Nunca"
 OPTION_MONTHLY:0 "Todo mês"
 OPTION_HALFYEAR:0 "A cada seis meses"
 OPTION_YEARLY:0 "Uma vez por ano"
 OPTION_FIVE_YEAR:0 "A cada cinco anos"
 OPTION_NO_AUTOSAVE:0 "Não salvar automaticamente"
 SETTINGS_CATEGORY_ACCOUNT:0 "Conta"
 SETTINGS_CATEGORY_SYSTEM:0 "Sistema"
 SETTINGS_CATEGORY_CONTROLS:0 "Controles"
 SETTINGS_CATEGORY_CAMERA:0 "Câmera"
 SETTINGS_CATEGORY_AUDIO:0 "Áudio"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Vínculos de Comando"
 DISCARD:0 "Descartar"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "Configurações"
 REQUIRES_RESTART:0 "É necessário reiniciar"
 REQUIRE_RESTART_DESCRIPTION:0 "Algumas configurações não entrarão em vigor até que você reinicie o jogo."
 SETTINGS_INPUT_REMAP_INPUT:0 "Remapear entrada"
 SETTINGS_INPUT_CONFIRM:0 "Confirmar"
 SETTINGS_INPUT_CANCEL:0 "Cancelar"
 SETTINGS_INPUT_CLEAR:0 "Apagar"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Salvar Perfil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Carregar Perfil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Redefinir Padrões"
 SETTINGS_INPUT_BINDING_TEXT:0 "Escolha um vínculo de comando para a ação "$INPUT_ACTION$":\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Aviso: este vínculo de comando já existe para "$INPUT_ACTION$"!\nPressionar "$SETTINGS_INPUT_CONFIRM$" apagará o vínculo anterior"
