l_braz_por:
 SETTINGS_PAGE_GRAPHICS: "Gráficos"
 SETTINGS_PAGE_GAME: "Jogo"
 SETTINGS_PAGE_SYSTEM: "Sistema"
 SETTINGS_PAGE_CONTROLS: "Controles"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Interface"
 SETTINGS_PAGE_AUDIO: "Áudio"
 SETTINGS_CATEGORY_SCREEN: "Tela"
 SETTINGS_CATEGORY_QUALITY: "Qualidade"
 OPTION_EASY: "Fácil"
 OPTION_NORMAL: "Normal"
 OPTION_HARD: "Difícil"
 OPTION_NEVER: "Nunca"
 OPTION_MONTHLY: "Todo mês"
 OPTION_HALFYEAR: "A cada seis meses"
 OPTION_YEARLY: "Uma vez por ano"
 OPTION_FIVE_YEAR: "A cada cinco anos"
 OPTION_NO_AUTOSAVE: "Não salvar automaticamente"
 SETTINGS_CATEGORY_ACCOUNT: "Conta"
 SETTINGS_CATEGORY_SYSTEM: "Sistema"
 SETTINGS_CATEGORY_CONTROLS: "Controles"
 SETTINGS_CATEGORY_CAMERA: "Câmera"
 SETTINGS_CATEGORY_AUDIO: "Áudio"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Vínculos de Comando"
 DISCARD: "Descartar"
 APPLY: "Aplicar"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Configurações"
 REQUIRES_RESTART: "É necessário reiniciar"
 REQUIRE_RESTART_DESCRIPTION: "Algumas configurações não entrarão em vigor até que você reinicie o jogo."
 SETTINGS_INPUT_REMAP_INPUT: "Remapear entrada"
 SETTINGS_INPUT_CONFIRM: "Confirmar"
 SETTINGS_INPUT_CANCEL: "Cancelar"
 SETTINGS_INPUT_CLEAR: "Apagar"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Salvar Perfil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Carregar Perfil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Redefinir Padrões"
 SETTINGS_INPUT_BINDING_TEXT: "Escolha um vínculo de comando para a ação \"$INPUT_ACTION$\":\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Aviso: este vínculo de comando já existe para \"$INPUT_ACTION$\"!\nPressionar \"$SETTINGS_INPUT_CONFIRM$\" apagará o vínculo anterior"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Aviso: este vínculo de comando não pode ser apenas de teclas modificadoras"
 SETTINGS_PAGE_ACCOUNT: "Conta"
 SETTING_TELEMETRY_CONSENT: "Enviar dados opcionais de telemetria"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Consentimento de Telemetria#!\nPermite o envio de dados opcionais de telemetria para a Paradox Interactive."
