l_turkish:
 SETTINGS_PAGE_GRAPHICS:0 "Grafikler"
 SETTINGS_PAGE_GAME:0 "Oyun"
 SETTINGS_PAGE_SYSTEM:0 "Sistem"
 SETTINGS_PAGE_CONTROLS:0 "Kontroller"
 SETTINGS_PAGE_EDITOR:0 "Editör"
 SETTINGS_PAGE_INTERFACE:0 "Arayüz"
 SETTINGS_PAGE_AUDIO:0 "Ses"
 SETTINGS_CATEGORY_SCREEN:0 "Ekran"
 SETTINGS_CATEGORY_QUALITY:0 "Kalite"
 OPTION_EASY:0 "Kolay"
 OPTION_NORMAL:0 "Normal"
 OPTION_HARD:0 "Zor"
 OPTION_NEVER:0 "Asla"
 OPTION_MONTHLY:0 "Ayda bir"
 OPTION_HALFYEAR:0 "Altı ayda bir"
 OPTION_YEARLY:0 "Yılda bir"
 OPTION_FIVE_YEAR:0 "Beş yılda bir"
 OPTION_NO_AUTOSAVE:0 "Otomatik kaydetmesin"
 SETTINGS_CATEGORY_ACCOUNT:0 "Hesap"
 SETTINGS_CATEGORY_SYSTEM:0 "Sistem"
 SETTINGS_CATEGORY_CONTROLS:0 "Kontroller"
 SETTINGS_CATEGORY_CAMERA:0 "Kamera"
 SETTINGS_CATEGORY_AUDIO:0 "Ses"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Tuş Atamaları"
 DISCARD:0 "Çıkar"
 SAVE_AND_CLOSE:0 "Tamam"
 SETTINGS:0 "Ayarlar"
 REQUIRES_RESTART:0 "Yeniden başlatma gerekli"
 REQUIRE_RESTART_DESCRIPTION:0 "Bazı ayar değişiklikleri oyun yeniden başlatıldıktan sonra etkinleşir."
 SETTINGS_INPUT_REMAP_INPUT:0 "Tuşları yeniden ata"
 SETTINGS_INPUT_CONFIRM:0 "Onayla"
 SETTINGS_INPUT_CANCEL:0 "İptal Et"
 SETTINGS_INPUT_CLEAR:0 "Temizle"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Profili Kaydet"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Profil Yükle"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Varsayılana Sıfırla"
 SETTINGS_INPUT_BINDING_TEXT:0 "Lütfen "$INPUT_ACTION$" eylemi için bir tuş ata:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Dikkat: Bu tuş ataması önceden "$INPUT_ACTION$" için ayarlanmış!\n"$SETTINGS_INPUT_CONFIRM$" tuşuna basmak eski atamayı kaldırır."
