l_russian:
 SETTINGS_PAGE_GRAPHICS:0 "Графика"
 SETTINGS_PAGE_GAME:0 "Игра"
 SETTINGS_PAGE_SYSTEM:0 "Система"
 SETTINGS_PAGE_CONTROLS:0 "Управление"
 SETTINGS_PAGE_EDITOR:0 "Редактор"
 SETTINGS_PAGE_INTERFACE:0 "Интерфейс"
 SETTINGS_PAGE_AUDIO:0 "Звук"
 SETTINGS_CATEGORY_SCREEN:0 "Экран"
 SETTINGS_CATEGORY_QUALITY:0 "Качество"
 OPTION_EASY:0 "Легко"
 OPTION_NORMAL:0 "Нормально"
 OPTION_HARD:0 "Сложно"
 OPTION_NEVER:0 "Никогда"
 OPTION_MONTHLY:0 "Каждый месяц"
 OPTION_HALFYEAR:0 "Каждые полгода"
 OPTION_YEARLY:0 "Каждый год"
 OPTION_FIVE_YEAR:0 "Каждые пять лет"
 OPTION_NO_AUTOSAVE:0 "Не выполнять автосохранение"
 SETTINGS_CATEGORY_ACCOUNT:0 "Учетная запись"
 SETTINGS_CATEGORY_SYSTEM:0 "Система"
 SETTINGS_CATEGORY_CONTROLS:0 "Управление"
 SETTINGS_CATEGORY_CAMERA:0 "Камера"
 SETTINGS_CATEGORY_AUDIO:0 "Звук"
 SETTINGS_CATEGORY_GUI:0 "Интерфейс"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Привязка клавиш ввода"
 DISCARD:0 "Отменить"
 SAVE_AND_CLOSE:0 "ОК"
 SETTINGS:0 "Настройки"
 REQUIRES_RESTART:0 "Требуется перезапуск"
 REQUIRE_RESTART_DESCRIPTION:0 "Некоторые изменения вступят в силу только после перезапуска."
 SETTINGS_INPUT_REMAP_INPUT:0 "Перезадать ввод"
 SETTINGS_INPUT_CONFIRM:0 "Подтвердить"
 SETTINGS_INPUT_CANCEL:0 "Отменить"
 SETTINGS_INPUT_CLEAR:0 "Удалить"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Сохранить профиль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Загрузить профиль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "По умолчанию"
 SETTINGS_INPUT_BINDING_TEXT:0 "Пожалуйста, привяжите клавишу к действию «$INPUT_ACTION$»:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Внимание: Эта клавиша уже привязана к действию «$INPUT_ACTION$»!\nНажав «$SETTINGS_INPUT_CONFIRM$», вы удалите предыдущую привязку"

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 RESTORE:0 "Восстановить"
