l_spanish:
 SETTINGS_PAGE_GRAPHICS: "Gráficos"
 SETTINGS_PAGE_GAME: "Partida"
 SETTINGS_PAGE_SYSTEM: "Sistema"
 SETTINGS_PAGE_CONTROLS: "Controles"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Interfaz"
 SETTINGS_PAGE_AUDIO: "Audio"
 SETTINGS_CATEGORY_SCREEN: "Pantalla"
 SETTINGS_CATEGORY_QUALITY: "Calidad"
 OPTION_EASY: "Fácil"
 OPTION_NORMAL: "Normal"
 OPTION_HARD: "Difícil"
 OPTION_NEVER: "Nunca"
 OPTION_MONTHLY: "Cada mes"
 OPTION_HALFYEAR: "Cada medio año"
 OPTION_YEARLY: "Cada año"
 OPTION_FIVE_YEAR: "Cada cinco años"
 OPTION_NO_AUTOSAVE: "No guardar automáticamente"
 SETTINGS_CATEGORY_ACCOUNT: "Cuenta"
 SETTINGS_CATEGORY_SYSTEM: "Sistema"
 SETTINGS_CATEGORY_CONTROLS: "Controles"
 SETTINGS_CATEGORY_CAMERA: "Cámara"
 SETTINGS_CATEGORY_AUDIO: "Audio"
 SETTINGS_CATEGORY_GUI: "Interfaz"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Teclas asignadas"
 DISCARD: "Descartar"
 APPLY: "Aplicar"
 SAVE_AND_CLOSE: "Vale"
 SETTINGS: "Configuración"
 REQUIRES_RESTART: "Requiere reiniciar"
 REQUIRE_RESTART_DESCRIPTION: "Algunos ajustes no tendrán efecto hasta que reinicies el juego."
 SETTINGS_INPUT_REMAP_INPUT: "Reasignar asignaciones"
 SETTINGS_INPUT_CONFIRM: "Confirmar"
 SETTINGS_INPUT_CANCEL: "Cancelar"
 SETTINGS_INPUT_CLEAR: "Borrar"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Guardar perfil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Cargar perfil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Predeterminado"
 SETTINGS_INPUT_BINDING_TEXT: "Asignar una tecla para la acción «$INPUT_ACTION$»:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Atención: Esta asignación ya existe para «$INPUT_ACTION$»\nPulsar «$SETTINGS_INPUT_CONFIRM$» borrará la asignación anterior"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Advertencia: La asignación no puede constar solo de teclas modificadoras"
 SETTINGS_PAGE_ACCOUNT: "Cuenta"
 SETTING_TELEMETRY_CONSENT: "Enviar datos de telemetría opcionales"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Consentimiento para telemetría#!\nPermitir el envío de datos de telemetría opcionales a Paradox Interactive."
