l_french:
 SETTINGS_PAGE_GRAPHICS:0 "Graphismes"
 SETTINGS_PAGE_GAME:0 "Jeu"
 SETTINGS_PAGE_SYSTEM:0 "Système"
 SETTINGS_PAGE_CONTROLS:0 "Contrôles"
 SETTINGS_PAGE_EDITOR:0 "Éditeur"
 SETTINGS_PAGE_INTERFACE:0 "Interfaces"
 SETTINGS_PAGE_AUDIO:0 "Son"
 SETTINGS_CATEGORY_SCREEN:0 "Écran"
 SETTINGS_CATEGORY_QUALITY:0 "Qualité"
 OPTION_EASY:0 "Facile"
 OPTION_NORMAL:0 "Normale"
 OPTION_HARD:0 "Difficile"
 OPTION_NEVER:0 "Jamais"
 OPTION_MONTHLY:0 "Chaque mois"
 OPTION_HALFYEAR:0 "Tous les 6 mois"
 OPTION_YEARLY:0 "Chaque année"
 OPTION_FIVE_YEAR:0 "Tous les 5 ans"
 OPTION_NO_AUTOSAVE:0 "Pas de sauvegarde automatique"
 SETTINGS_CATEGORY_ACCOUNT:0 "Compte"
 SETTINGS_CATEGORY_SYSTEM:0 "Système"
 SETTINGS_CATEGORY_CONTROLS:0 "Contrôles"
 SETTINGS_CATEGORY_CAMERA:0 "Caméra"
 SETTINGS_CATEGORY_AUDIO:0 "Son"
 SETTINGS_CATEGORY_GUI:0 "Interfaces graphiques"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Attributions"
 DISCARD:0 "Annuler les changements"
 SAVE_AND_CLOSE:0 "Sauver et fermer"
 SETTINGS:0 "Paramètres"
 REQUIRES_RESTART:0 "Nécessite de relancer"
 REQUIRE_RESTART_DESCRIPTION:0 "Certains paramètres ne seront pris en compte qu'une fois le jeu relancé."
 SETTINGS_INPUT_REMAP_INPUT:0 "Réattribuer"
 SETTINGS_INPUT_CONFIRM:0 "Confirmer"
 SETTINGS_INPUT_CANCEL:0 "Annuler"
 SETTINGS_INPUT_CLEAR:0 "Effacer"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Sauvegarder profil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Charger profil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Réinitialiser"
 SETTINGS_INPUT_BINDING_TEXT:0 "Veuillez choisir une attribution pour l'action '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Avertissement : cette attribution existe déjà pour '$INPUT_ACTION$'!\nAppuyer sur '$SETTINGS_INPUT_CONFIRM$' effacera l'ancienne attribution"

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 RESTORE:0 "Réinitialiser"
