l_german:
 SETTINGS_PAGE_GRAPHICS: "Grafikeinstellungen"
 SETTINGS_PAGE_GAME: "Spiel"
 SETTINGS_PAGE_SYSTEM: "System"
 SETTINGS_PAGE_CONTROLS: "Steuerung"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_INTERFACE: "Benutzeroberfläche"
 SETTINGS_PAGE_AUDIO: "Audio"
 SETTINGS_CATEGORY_SCREEN: "Anzeige"
 SETTINGS_CATEGORY_QUALITY: "Qualität"
 OPTION_EASY: "Einfach"
 OPTION_NORMAL: "Normal"
 OPTION_HARD: "Schwer"
 OPTION_NEVER: "Niemals"
 OPTION_MONTHLY: "Monatlich"
 OPTION_HALFYEAR: "Halbjährlich"
 OPTION_YEARLY: "Jährlich"
 OPTION_FIVE_YEAR: "Alle fünf Jahre"
 OPTION_NO_AUTOSAVE: "Kein Autospeichern"
 SETTINGS_CATEGORY_ACCOUNT: "Konto"
 SETTINGS_CATEGORY_SYSTEM: "System"
 SETTINGS_CATEGORY_CONTROLS: "Steuerung"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_AUDIO: "Audio"
 SETTINGS_CATEGORY_GUI: "Grafische Oberfläche"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Tastaturbelegung"
 DISCARD: "Verwerfen"
 APPLY: "Anwenden"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Einstellungen"
 REQUIRES_RESTART: "Benötigt Neustart"
 REQUIRE_RESTART_DESCRIPTION: "Einige Einstellungen erfordern einen Neustart des Spiels."
 SETTINGS_INPUT_REMAP_INPUT: "Belegung ändern"
 SETTINGS_INPUT_CONFIRM: "Bestätigen"
 SETTINGS_INPUT_CANCEL: "Abbrechen"
 SETTINGS_INPUT_CLEAR: "Läschen"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Profil speichern"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Profil laden"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Auf Standard zurücksetzen"
 SETTINGS_INPUT_BINDING_TEXT: "Bitte eine Tastenbelegung für '$INPUT_ACTION$' eingeben:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Achtung: Diese Tastaturbelegung gibt es bereits für '$INPUT_ACTION$'!\nDurch Drücken von '$SETTINGS_INPUT_CONFIRM$' wird die alte Belegung aufgehoben"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Warnung: Die Tastenbelegung kann nicht nur aus Modifikatortasten bestehen"
 SETTINGS_PAGE_ACCOUNT: "Konto"
 SETTING_TELEMETRY_CONSENT: "Optionale Telemetriedaten schicken"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Telemetriezustimmung#!\nErlaubt das Verschicken optionaler Telemetriedaten an Paradox Interactive."
