l_korean:
 SETTINGS_PAGE_GRAPHICS: "그래픽"
 SETTINGS_PAGE_GAME: "게임"
 SETTINGS_PAGE_SYSTEM: "시스템"
 SETTINGS_PAGE_CONTROLS: "조작"
 SETTINGS_PAGE_EDITOR: "에디터"
 SETTINGS_PAGE_INTERFACE: "인터페이스"
 SETTINGS_PAGE_AUDIO: "오디오"
 SETTINGS_CATEGORY_SCREEN: "화면"
 SETTINGS_CATEGORY_QUALITY: "품질"
 OPTION_EASY: "쉬움"
 OPTION_NORMAL: "보통"
 OPTION_HARD: "어려움"
 OPTION_NEVER: "없음"
 OPTION_MONTHLY: "1달마다"
 OPTION_HALFYEAR: "반년마다"
 OPTION_YEARLY: "1년마다"
 OPTION_FIVE_YEAR: "5년마다"
 OPTION_NO_AUTOSAVE: "자동 저장 없음"
 SETTINGS_CATEGORY_ACCOUNT: "계정"
 SETTINGS_CATEGORY_SYSTEM: "시스템"
 SETTINGS_CATEGORY_CONTROLS: "조작"
 SETTINGS_CATEGORY_CAMERA: "카메라"
 SETTINGS_CATEGORY_AUDIO: "오디오"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "입력키 지정"
 DISCARD: "취소"
 APPLY: "적용"
 SAVE_AND_CLOSE: "확인"
 SETTINGS: "설정"
 REQUIRES_RESTART: "재시작 필요"
 REQUIRE_RESTART_DESCRIPTION: "일부 설정은 게임을 재시작해야 제대로 적용됩니다."
 SETTINGS_INPUT_REMAP_INPUT: "입력키 재지정"
 SETTINGS_INPUT_CONFIRM: "확인"
 SETTINGS_INPUT_CANCEL: "취소"
 SETTINGS_INPUT_CLEAR: "초기화"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "프로필 저장"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "프로필 불러오기"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "기본값으로 초기화"
 SETTINGS_INPUT_BINDING_TEXT: "$INPUT_ACTION$' 행동에 사용할 입력키를 선택하십시오.\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "경고: 해당 입력키는 이미 '$INPUT_ACTION$'에 사용 중입니다!\n'$SETTINGS_INPUT_CONFIRM$' 키를 누르면 기존에 지정된 입력키를 초기화합니다"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "경고: 입력키는 보조 키로만 구성할 수 없습니다."
