l_spanish:
 SETTINGS_PAGE_GRAPHICS:0 "Gráficos"
 SETTINGS_PAGE_GAME:0 "Partida"
 SETTINGS_PAGE_SYSTEM:0 "Sistema"
 SETTINGS_PAGE_CONTROLS:0 "Controles"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE:0 "Interfaz"
 SETTINGS_PAGE_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_SCREEN:0 "Pantalla"
 SETTINGS_CATEGORY_QUALITY:0 "Calidad"
 OPTION_EASY:0 "Fácil"
 OPTION_NORMAL:0 "Normal"
 OPTION_HARD:0 "Difícil"
 OPTION_NEVER:0 "Nunca"
 OPTION_MONTHLY:0 "Cada mes"
 OPTION_HALFYEAR:0 "Cada medio año"
 OPTION_YEARLY:0 "Cada año"
 OPTION_FIVE_YEAR:0 "Cada cinco años"
 OPTION_NO_AUTOSAVE:0 "No guardar automáticamente"
 SETTINGS_CATEGORY_ACCOUNT:0 "Cuenta"
 SETTINGS_CATEGORY_SYSTEM:0 "Sistema"
 SETTINGS_CATEGORY_CONTROLS:0 "Controles"
 SETTINGS_CATEGORY_CAMERA:0 "Cámara"
 SETTINGS_CATEGORY_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_GUI:0 "Interfaz"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Teclas asignadas"
 DISCARD:0 "Descartar"
 SAVE_AND_CLOSE:0 "Vale"
 SETTINGS:0 "Configuración"
 REQUIRES_RESTART:0 "Requiere reiniciar"
 REQUIRE_RESTART_DESCRIPTION:0 "Algunos ajustes no tendrán efecto hasta que reinicies el juego."
 SETTINGS_INPUT_REMAP_INPUT:0 "Reasignar asignaciones"
 SETTINGS_INPUT_CONFIRM:0 "Confirmar"
 SETTINGS_INPUT_CANCEL:0 "Cancelar"
 SETTINGS_INPUT_CLEAR:0 "Borrar"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Guardar perfil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Cargar perfil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Predeterminado"
 SETTINGS_INPUT_BINDING_TEXT:0 "Asignar una tecla para la acción «$INPUT_ACTION$»:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Atención: este asignación ya existe para «$INPUT_ACTION$»\nPulsar «$SETTINGS_INPUT_CONFIRM$» borrará la asignación anterior"

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 RESTORE:0 "Restaurar"
