l_french:
 SETTINGS_PAGE_GRAPHICS: "Graphismes"
 SETTINGS_PAGE_GAME: "Jeu"
 SETTINGS_PAGE_SYSTEM: "Système"
 SETTINGS_PAGE_CONTROLS: "Contrôles"
 SETTINGS_PAGE_EDITOR: "Éditeur"
 SETTINGS_PAGE_INTERFACE: "Interfaces"
 SETTINGS_PAGE_AUDIO: "Son"
 SETTINGS_CATEGORY_SCREEN: "Écran"
 SETTINGS_CATEGORY_QUALITY: "Qualité"
 OPTION_EASY: "Facile"
 OPTION_NORMAL: "Normale"
 OPTION_HARD: "Difficile"
 OPTION_NEVER: "Jamais"
 OPTION_MONTHLY: "Chaque mois"
 OPTION_HALFYEAR: "Tous les 6 mois"
 OPTION_YEARLY: "Chaque année"
 OPTION_FIVE_YEAR: "Tous les 5 ans"
 OPTION_NO_AUTOSAVE: "Pas de sauvegarde automatique"
 SETTINGS_CATEGORY_ACCOUNT: "Compte"
 SETTINGS_CATEGORY_SYSTEM: "Système"
 SETTINGS_CATEGORY_CONTROLS: "Contrôles"
 SETTINGS_CATEGORY_CAMERA: "Caméra"
 SETTINGS_CATEGORY_AUDIO: "Son"
 SETTINGS_CATEGORY_GUI: "Interfaces graphiques"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Attributions"
 DISCARD: "Annuler les changements"
 APPLY: "Appliquer"
 SAVE_AND_CLOSE: "Sauver et fermer"
 SETTINGS: "Paramètres"
 REQUIRES_RESTART: "Nécessite de relancer"
 REQUIRE_RESTART_DESCRIPTION: "Certains paramètres ne seront pris en compte qu'une fois le jeu relancé."
 SETTINGS_INPUT_REMAP_INPUT: "Réattribuer"
 SETTINGS_INPUT_CONFIRM: "Confirmer"
 SETTINGS_INPUT_CANCEL: "Annuler"
 SETTINGS_INPUT_CLEAR: "Effacer"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Sauvegarder profil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Charger profil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Réinitialiser"
 SETTINGS_INPUT_BINDING_TEXT: "Veuillez choisir une attribution pour l'action '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Avertissement : cette attribution existe déjà pour '$INPUT_ACTION$'!\nAppuyer sur '$SETTINGS_INPUT_CONFIRM$' effacera l'ancienne attribution"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Attention : l'attribution ne peut pas être constituée uniquement de touches de modification"
 SETTINGS_PAGE_ACCOUNT: "Compte"
 SETTING_TELEMETRY_CONSENT: "Envoyer les données de télémétrie optionnelles"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Consentement télémétrie#!\nAutoriser l’envoi de données de télémétrie optionnelles à Paradox Interactive."
