l_simp_chinese:
 SETTINGS_PAGE_GRAPHICS: "图像"
 SETTINGS_PAGE_GAME: "游戏"
 SETTINGS_PAGE_SYSTEM: "系统"
 SETTINGS_PAGE_CONTROLS: "控制"
 SETTINGS_PAGE_EDITOR: "编辑器"
 SETTINGS_PAGE_INTERFACE: "界面"
 SETTINGS_PAGE_AUDIO: "声音"
 SETTINGS_CATEGORY_SCREEN: "屏幕"
 SETTINGS_CATEGORY_QUALITY: "质量"
 OPTION_EASY: "简单"
 OPTION_NORMAL: "正常"
 OPTION_HARD: "困难"
 OPTION_NEVER: "永不"
 OPTION_MONTHLY: "每月"
 OPTION_HALFYEAR: "每半年"
 OPTION_YEARLY: "每年"
 OPTION_FIVE_YEAR: "每五年"
 OPTION_NO_AUTOSAVE: "禁用自动存档"
 SETTINGS_CATEGORY_ACCOUNT: "账号"
 SETTINGS_CATEGORY_SYSTEM: "系统"
 SETTINGS_CATEGORY_CONTROLS: "控制"
 SETTINGS_CATEGORY_CAMERA: "视角"
 SETTINGS_CATEGORY_AUDIO: "声音"
 SETTINGS_CATEGORY_GUI: "图形用户界面"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "输入绑定"
 DISCARD: "放弃"
 APPLY: "应用"
 SAVE_AND_CLOSE: "确定"
 SETTINGS: "设置"
 REQUIRES_RESTART: "需要重启游戏"
 REQUIRE_RESTART_DESCRIPTION: "部分设置需要重启游戏后才能生效。"
 SETTINGS_INPUT_REMAP_INPUT: "重映射输入"
 SETTINGS_INPUT_CONFIRM: "确认"
 SETTINGS_INPUT_CANCEL: "取消"
 SETTINGS_INPUT_CLEAR: "清除"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "保存档案"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "加载档案"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "重置为默认值"
 SETTINGS_INPUT_BINDING_TEXT: "请为“$INPUT_ACTION$”行动选择一个输入绑定：\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "警告：这个输入绑定对于“$INPUT_ACTION$”已存在！\n按“$SETTINGS_INPUT_CONFIRM$”会清除旧绑定"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "警告：输入绑定不能仅由修饰键组成"
 SETTINGS_PAGE_ACCOUNT: "账号"
 SETTING_TELEMETRY_CONSENT: "发送可选的遥测数据"
 SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T 遥测数据同意#!\n允许向 Paradox Interactive 发送可选的遥测数据。"
