l_german:
 SETTINGS_PAGE_GRAPHICS:0 "Grafikeinstellungen"
 SETTINGS_PAGE_GAME:0 "Spiel"
 SETTINGS_PAGE_SYSTEM:0 "System"
 SETTINGS_PAGE_CONTROLS:0 "Steuerung"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE:0 "Benutzeroberfläche"
 SETTINGS_PAGE_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_SCREEN:0 "Anzeige"
 SETTINGS_CATEGORY_QUALITY:0 "Qualität"
 OPTION_EASY:0 "Einfach"
 OPTION_NORMAL:0 "Normal"
 OPTION_HARD:0 "Schwer"
 OPTION_NEVER:0 "Niemals"
 OPTION_MONTHLY:0 "Monatlich"
 OPTION_HALFYEAR:0 "Halbjährlich"
 OPTION_YEARLY:0 "Jährlich"
 OPTION_FIVE_YEAR:0 "Alle fünf Jahre"
 OPTION_NO_AUTOSAVE:0 "Kein Autospeichern"
 SETTINGS_CATEGORY_ACCOUNT:0 "Konto"
 SETTINGS_CATEGORY_SYSTEM:0 "System"
 SETTINGS_CATEGORY_CONTROLS:0 "Steuerung"
 SETTINGS_CATEGORY_CAMERA:0 "Kamera"
 SETTINGS_CATEGORY_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_GUI:0 "Grafische Oberfläche"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Tastaturbelegung"
 DISCARD:0 "Verwerfen"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "Einstellungen"
 REQUIRES_RESTART:0 "Benötigt Neustart"
 REQUIRE_RESTART_DESCRIPTION:0 "Einige Einstellungen erfordern einen Neustart des Spiels."
 SETTINGS_INPUT_REMAP_INPUT:0 "Belegung ändern"
 SETTINGS_INPUT_CONFIRM:0 "Bestätigen"
 SETTINGS_INPUT_CANCEL:0 "Abbrechen"
 SETTINGS_INPUT_CLEAR:0 "Läschen"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Profil speichern"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Profil laden"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Auf Standard zurücksetzen"
 SETTINGS_INPUT_BINDING_TEXT:0 "Bitte eine Tastenbelegung für '$INPUT_ACTION$' eingeben:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Achtung: Diese Tastaturbelegung gibt es bereits für '$INPUT_ACTION$'!\nDurch Drücken von '$SETTINGS_INPUT_CONFIRM$' wird die alte Belegung aufgehoben"

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 RESTORE:0 "Zurücksetzen"
