l_turkish:
 SETTINGS_PAGE_GRAPHICS: "Grafikler"
 SETTINGS_PAGE_GAME: "Oyun"
 SETTINGS_PAGE_SYSTEM: "Sistem"
 SETTINGS_PAGE_CONTROLS: "Kontroller"
 SETTINGS_PAGE_EDITOR: "Editör"
 SETTINGS_PAGE_INTERFACE: "Arayüz"
 SETTINGS_PAGE_AUDIO: "Ses"
 SETTINGS_CATEGORY_SCREEN: "Ekran"
 SETTINGS_CATEGORY_QUALITY: "Kalite"
 OPTION_EASY: "Kolay"
 OPTION_NORMAL: "Normal"
 OPTION_HARD: "Zor"
 OPTION_NEVER: "Asla"
 OPTION_MONTHLY: "Ayda bir"
 OPTION_HALFYEAR: "Altı ayda bir"
 OPTION_YEARLY: "Yılda bir"
 OPTION_FIVE_YEAR: "Beş yılda bir"
 OPTION_NO_AUTOSAVE: "Otomatik kaydetmesin"
 SETTINGS_CATEGORY_ACCOUNT: "Hesap"
 SETTINGS_CATEGORY_SYSTEM: "Sistem"
 SETTINGS_CATEGORY_CONTROLS: "Kontroller"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_AUDIO: "Ses"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Tuş Atamaları"
 DISCARD: "Çıkar"
 APPLY: "Uygula"
 SAVE_AND_CLOSE: "Tamam"
 SETTINGS: "Ayarlar"
 REQUIRES_RESTART: "Yeniden başlatma gerekli"
 REQUIRE_RESTART_DESCRIPTION: "Bazı ayar değişiklikleri oyun yeniden başlatıldıktan sonra etkinleşir."
 SETTINGS_INPUT_REMAP_INPUT: "Tuşları yeniden ata"
 SETTINGS_INPUT_CONFIRM: "Onayla"
 SETTINGS_INPUT_CANCEL: "İptal Et"
 SETTINGS_INPUT_CLEAR: "Temizle"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Profili Kaydet"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Profil Yükle"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Varsayılana Sıfırla"
 SETTINGS_INPUT_BINDING_TEXT: "Lütfen \"$INPUT_ACTION$\" eylemi için bir tuş ata:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Dikkat: Bu tuş ataması önceden \"$INPUT_ACTION$\" için ayarlanmış!\n\"$SETTINGS_INPUT_CONFIRM$\" tuşuna basmak eski atamayı kaldırır."
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Dikkat: Tuş ataması sadece değiştirici tuşlardan oluşamaz."
