l_german:
 SETTING_VALUE_WARNING:0 "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X Eine Skalierung über einen Wert von $VALUE|%0$ führt dazu, dass Benutzeroberflächen außerhalb des Bildschirms liegen#!"
 RECOMMENDED_GUI_SCALE:1 "Eine Skalierung über einen Wert von $VALUE|%0$ führt dazu, dass Benutzeroberflächen außerhalb des Bildschirms liegen"
