l_german:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ Sekunden"
 SETTING_VALUE_MINUTES: "$VALUE$ Minuten"
 #Graphics
 SETTING_RENDERER: "Renderer"
 SETTING_RENDERER_TOOLTIP: "Legt die Art des Renderers fest, der verwendet werden soll."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Synchronisiert die Bildfrequenz des Spiels mit der des Bildschirms, um ein Verschwimmen des Bildes zu reduzieren.\n\nEine Deaktivierung kann die Leistung verbessern."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Porträt-Multisampling"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Der Einsatz von Multi-Sampling für Alpha-To-Coverage deckt das Haar glatter ab.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MULTI_SAMPLING: "Multisampling"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Die Verwendung von Multi-Sample-Anti-Aliasing (MSAA) macht die Kanten der Bilder glatter.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_ANTI_ALIASING: "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Die Verwendung von Anti-Aliasing macht die Kanten der Bilder glatter.\n\nFXAA wird empfohlen."
 OPTION_ANTI_ALIASING_DISABLED: "Deaktiviert"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Upscaling-Methode"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nUpscaling-Methoden können verwendet werden, um eine höhere Anzeigeauflösung durch algorithmisches Upsampling zu erreichen. Dies kann die Leistung verbessern, aber auch zu visuellen Artefakten oder anderem unerwarteten Verhalten führen.\n\nDie verfügbaren Upscale-Methoden können von Ihrer Grafikkarte abhängen."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Upscaling-Qualität"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nLegt den Schwerpunkt der Hochskalierungsmethode von höchster Qualität auf höchste Leistung."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra-Qualität"
 OPTION_UPSCALE_QUALITY_QUALITY: "Qualität"
 OPTION_UPSCALE_QUALITY_BALANCED: "Ausgewogen"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Leistung"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Ultra-Leistung"
 SETTING_ANISOTROPIC_FILTERING: "Anisotrope Filterung"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Die Nutzung von anisotropem Filtern führt dazu, dass Oberflächen besser aussehen.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_RESOLUTION: "Auflösung"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Legt die Auflösungsqualität des Spiels fest.\n\nEine niedrigere Auflösung kann die Leistung erhöhen.\n\n#X Die Spielauflösung bei nicht unterstützten Seitenverhältnissen kann dafür sorgen, dass die Oberfläche außerhalb des Bildschirms angezeigt wird#!"
 SETTING_WINDOWED_RESOLUTION: "Fensterauflösung"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Legt die Auflösung des Spiels fest, wenn das Spiel im Fenster läuft.\n\nMuss im Format #b ZAHL#!x#b ZAHL#! vorliegen.\n\n#X Die Spielauflösung bei nicht unterstützten Seitenverhältnissen kann dafür sorgen, dass die Oberfläche außerhalb des Bildschirms angezeigt wird#!"
 SETTING_RENDER_SCALE: "Render-Skalierung"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nDas Skalieren der Render-Auflösung des Spiels im Verhältnis zur Hauptauflösung mit Ausnahme der Benutzeroberfläche.\n\nNiedrigere Einstellungen können die Leistung verbessern, aber die allgemeine Bildqualität verschlechtern. Werden 100 % Bildqualität überschritten, wird dies sehr wahrscheinlich die Leistung verschlechtern."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Anzeige"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Falls mehrere Monitore angeschlossen sind, wählt man hier aus, welchen das Spiel nutzen soll."
 SETTING_GRAPHICS_DEVICE: "Grafikkarte"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Wählt aus, welche Grafikkarte das Spiel nutzen soll.\n\nEine integrierte Grafikkarte oder einen Software-Renderer zu benutzen, kann die Leistung reduzieren."
 SETTING_SHADOW_MAP_RESOLUTION: "Schattenqualität"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Bestimmt die Auflösung, mit der Schatten gerendert werden, falls diese aktiviert sind.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_DISPLAY_MODE: "Anzeigemodus"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Bestimmt, wie das Spiel auf dem Bildschirm angezeigt wird"
 SETTING_BLOOM_QUALITY: "Bloom"
 SETTING_MESH_LOD_BIAS: "Objektqualität"
 SETTING_MESH_LOD_FADE: "Objektübergänge"
 SETTING_TERRAIN_SMOOTHING: "Geländeglättung"
 OPTION_FULLSCREEN: "Vollbild"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Das Spiel nutzt den gesamten Bildschirm. Die Auflösungseinstellung legt fest, wie scharf das Bild dargestellt wird."
 OPTION_WINDOWED: "Fenster"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Öffnet das Spiel im Fenstermodus. Die Auflösungseinstellung legt die Größe des Fensters fest."
 OPTION_DISABLED: "Deaktiviert"
 OPTION_OFF: "Aus"
 OPTION_LOW: "Niedrig"
 OPTION_MEDIUM: "Mittel"
 OPTION_HIGH: "Hoch"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Benutzerdefiniert"
 OPTION_DEFAULT: "Standard"
 SETTINGS_CATEGORY_UI: "Benutzeroberfläche"
 SETTINGS_CATEGORY_GAME: "Spiel"
 SETTING_TEXTURE_QUALITY: "Texturqualität"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nBestimmt die Auflösung der geladenen Texturen.\n\nEine niedrigere Einstellung kann die Leistung erhöhen."
 SETTING_QUALITY: "Qualitätsvoreinstellung"
 SETTING_SFX: "SFX"
 SETTING_UI: "Benutzeroberfläche"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Wählt eine Voreinstellung aus den unten aufgeführten erweiterten Grafikoptionen.\n\nEine niedrige Voreinstellung verbessert die Leistung."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Aktiviert einen „Bloom“-Effekt, bei dem extrem helle Lichter auf andere Teile des Bildes übergreifen.\n\nNiedrigere Einstellungen können die Leistung erhöhen."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Erlaubt der Schärfentiefe, eine Kameralinse zu simulieren und Punkte außerhalb des Bilds unscharf zu machen.\n\nDas Deaktivieren kann die Leistung verbessern."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Aktiviert einen Lens-Flare-Effekt, der in starken Bloom-Bereichen erscheint. Bloom muss aktiviert sein, damit der Effekt erscheint.\n\nDas Ausschalten des Effekts kann die Leistung erhöhen."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Aktiviert einen sekundären Lens-Flare-Effekt, der in starken Bloom-Bereichen erscheint. Bloom muss aktiviert sein, damit der Effekt erscheint.\n\nDas Ausschalten des Effekts kann die Leistung erhöhen."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Legt fest, ob Screen Space Ambient Occlusion auf die Karte angewendet wird.\n\nDas Deaktivieren kann die Leistung verbessern."
 SETTING_REFRACTION_TOOLTIP: "Bestimmt, ob Spiegelungen auf dem Wasser erscheinen oder nicht."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nSteuert die Qualität der Wasserrefraktionen, falls diese aktiviert sind.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nBestimmt die höchste Qualitätsstufe von Kartenobjekten (z. B. von Gebäuden).\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nBestimmt die Detailstufe für Kartenobjekte wie Einheitenmodelle.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Wenn diese Option eingeschaltet ist, gehen 3-D-Modelle beim Heran- und Herauszoomen nahtlos zwischen verschiedenen Detailstufen (LOD) über.\n\nDas Ausschalten kann die Leistung verbessern."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Legt fest, wie Stadt- und Provinznamen auf der Karte angezeigt werden."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Bestimmt, ob nicht passierbares Gelände innerhalb der Grenzen einer Nation auf der Karte enthalten sind oder nicht."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nBestimmt die Sprache der Benutzeroberfläche."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "E-Mail Eures Paradox-Kontos"
 SETTING_FRAMERATE_CAP: "Frameratebegrenzung"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nBegrenzung für die Bildwiederholungsrate (Frames pro Sekunde), die das Spiel rendert.\n\nNiedrigere Einstellungen können den Stromverbrauch senken."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Textur-Streaming"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTexturen werden nach Bedarf geladen.\n\nSenkt den Bedarf an GPU-Speicher, sorgt aber für zusätzliche CPU-Last. Kann die Leistung von GPUs mit kleinem Speicher verbessern."
 SETTING_TEXTURE_STREAMING_CACHE: "Textur-Streaming-Cachegröße"
 SETTING_VALUE_MB: "$VALUE$ MB"
 #GUI
 SETTING_ANIMATION_SPEED: "Animationsgeschwindigkeit"
 SETTING_GUI_SCALING: "GUI-Skalierung"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Legt die Größe der gesamten Benutzeroberfläche fest. Dies ist für höhere Bildschirmauflösungen besonders nützlich.\n\n#X Ein zu hoher Wert kann dazu führen, dass Benutzeroberflächen nicht richtig auf den Bildschirm passen!#!"
 SETTING_TOOLS_GUI_SCALING: "Werkzeuge-GUI-Skalierung"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Legt den Maßstab der Benutzeroberfläche der Werkzeuge fest. Nützlich bei höheren Bildschirmauflösungen.\n\n#X Eine zu hohe Einstellung führt dazu, dass die Benutzeroberfläche nicht richtig auf den Bildschirm passt!#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Mausschwenk"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Frei"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 Richtungen"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Deaktiviert"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nLegt fest, wie die Kamera sich verhält, wenn man mit der Maus schwenkt."
 SETTING_SCROLL_SPEED: "Schwenktempo"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nLegt fest, wie schnell die Karte schwenkt, wenn man Tastatur oder Maus verwendet."
 SETTING_CAMERA_ROTATION_SPEED: "Drehtempo der Kamera"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nDas Drehtempo der Kamera."
 SETTING_ZOOM_SPEED: "Zoomtempo"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nDas Zoomtempo der Kamera."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Zoomverhalten"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Relativer Zeiger"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Auf Zeiger zoomen"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Zeiger ignorieren"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nLegt fest, wie die Kamera sich relativ zum Mauszeiger beim Herein- und Herauszoomen verhält."
 SETTING_INPUT_DEVICE: "Eingabegerät"
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_POSTFIX: "Editor-Postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Befehl zum Öffnen des Editors"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Log-Befehl anzeigen"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Befehl zum Öffnen des Editors"
 SETTING_GRACEFUL_EXIT: "Kontrollierte Beendigung"
 SETTING_LANGUAGE: "Anzeigesprache"
 MOUSE_AND_KEYBOARD: "Maus & Tastatur"
 GAMEPAD: "Gamepad"
 SETTING_MULTISAMPLING_DISABLED: "Deaktiviert"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Deaktiviert"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Deaktiviert"
 #Editor
 SETTING_CAMERA_TILT: "Kameraneigung"
 SETTING_CAMERA_STRATEGY: "Kameratyp"
 SETTING_CENTERED_ZOOM_IN: "Zentrierter Zoom"
 SETTING_CAMERA_SPEED: "Kamerageschwindigkeit"
 CAMERA_TABLETOP: "Vogelperspektive"
 CAMERA_FPS: "Egoperspektive"
 CAMERA_WASD: "WASD-Stil"
 #Audio
 SETTING_Music: "Musik"
 SETTING_Ambient: "Umgebung"
 SETTING_Effects: "Effekte"
 SETTING_Master: "Hauptlautstärke"
 SETTING_VO: "Voiceover"
 SETTING_VO_TOOLTIP: "#T Voiceover-Lautstärke\n#!Steuert die Lautstärke des Voiceovers."
 SETTING_Master_TOOLTIP: "#T Hauptlautstärke\n#!Steuert die Lautstärke aller Töne und Musik im Spiel."
 SETTING_Music_TOOLTIP: "#T Musiklautstärke\n#!Steuert die Lautstärke der Hintergrundmusik."
 SETTING_Ambient_TOOLTIP: "#T Umgebungslautstärke\n#!Steuert die Lautstärke der Umgebungsatmosphäre."
 SETTING_SFX_TOOLTIP: "#T SFX-Lautstärke\n#!Steuert die Lautstärke von Soundeffekten, z. B. im Kampf."
 SETTING_UI_TOOLTIP: "#T UI-Lautstärke\n#!Steuert die Lautstärke der Benutzeroberfläche."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Debug-Log-Stufe"
 SETTING_AUDIO_DEVICE_PROFILE: "Audioprofil"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Wählen Sie ein Audioprofil, das zu Ihrem System passt."
 SETTING_AUDIO_OPTION_SPEAKERS: "Lautsprecher"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Standard-Mix für $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Kopfhörer"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Ein für $SETTING_AUDIO_OPTION_HEADPHONES$ angepasster Mix."
 SETTING_AUDIO_OPTION_TV: "Fernseher"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Ein Mix für $SETTING_AUDIO_OPTION_TV$ und Monitorlautsprecher."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Nachtmodus"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Leiserer Ton für Spiele bei Nacht; hohe Töne werden gedämpft und die dynamische Bandbreite komprimiert."
 SETTING_MUSIC_DENSITY: "Musikdichte"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Steuert das Verhältnis von Liedern, Stille und atmosphärischen Musikabschnitten\n\nIntensiv – Hauptsächlich Lieder, die nacheinander abgespielt werden, ähnlich einem Radiosender.\nAusgewogen – Die ideale Mischung aus Liedern, Stille und Atmosphäre.\nEntspannt – Hauptsächlich entspannende Musikabschnitte, die für mehr Atmosphäre bei einem mehrstündigen Spielerlebnis sorgen."
 #Game
 SETTING_AUTOSAVE: "Autospeicher-Intervall"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Legt fest, wie oft das Spiel automatisch gespeichert wird."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Legt fest, ob automatische Speicherstände in der Cloud gespeichert werden oder nicht."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Legt fest, ob die Kamera immer nach Norden zeigt oder nicht."
 NO_AUTOSAVE: "Kein Autospeichern"
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Datenübertragungstempo"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Legt das Maximaltempo für Speicherstandübertragungen in der Mehrspieler-Lobby fest.\n\nNiedrigere Einstellungen können die Netzwerkstabilität beim Beitritt zu Mehrspieler-Spielen verbessern, sich aber negativ auf die Mehrspieler-Ladezeiten auswirken."
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Karten-Editor-Autospeichern (Minuten)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Karten-Editor-Autospeichern-Intervall (Minuten)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Knoten-Editor-Schwenkmodus durch Ziehen"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Erleichterte Bedienung"
 SETTING_COLOR_BLIND_MODE: "Farbenblindheits-Modus"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Ändert die Farben, die in Spieltexten verwendet werden, damit man sie bei verschiedenen Arten von Farbenblindheit leichter erkennen kann."
