l_spanish:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ segundos"
 SETTING_VALUE_MINUTES:0 "$VALUE$ minutos"
 # Graphics
 SETTING_RENDERER:0 "Reproductor"
 SETTING_RENDERER_TOOLTIP:0 "Determina qué renderizador se usa."
 SETTING_VSYNC:0 "Sincronización vertical"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Iguala la tasa de fotogramas por segundo del juego y de tu monitor.\n\nSi se desactiva puede mejorar el rendimiento."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Muestreo múltiple de retratos"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Usa el muestreo múltiple en alfa a cobertura para que los efectos de cabello sean más suaves.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_MULTI_SAMPLING:0 "Suavizado de contornos por muestreo múltiple (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Emplea el suavizado de contornos por muestreo múltiple para que los bordes de las imágenes sean más definidos.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_ANTI_ALIASING:0 "Suavizado de contornos"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Los bordes de las imágenes se verán más suaves.\n\nSe recomienda el tipo FXAA."
 OPTION_ANTI_ALIASING_DISABLED:0 "Desactivado"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtrado de texturas"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Si se usa el filtrado anisótropo las texturas de las superficies se verán mejor.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_FULLSCREEN_RESOLUTION:0 "Resolución"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Ajusta la calidad de imagen del juego.\n\nLas resoluciones más bajas pueden mejorar el rendimiento.\n\n#X Las resoluciones con una relación de aspecto incompatible pueden hacer que las interfaces aparezcan fuera de la pantalla.#!"
 SETTING_WINDOWED_RESOLUTION:0 "Resolución en ventana"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Establece la resolución de la ventana de juego si se tiene seleccionado el modo Ventana.\n\nDebe tener el formato #b NÚMERO#!x#b NÚMERO#!.\n\n#X Las resoluciones con una relación de aspecto incompatible pueden hacer que las interfaces aparezcan fuera de la pantalla#!"
 SETTING_RENDER_SCALE:0 "Escala de renderización"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nLa escala de la resolución de renderizado del juego en relación con la resolución principal, excluyendo la interfaz de usuario.\n\nUn ajuste inferior puede aumentar el rendimiento, pero reducirá la fidelidad general. Si se elige un valor superior al 100 %, podría aumentar la fidelidad pero probablemente afecta al rendimiento."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Si tu equipo cuenta con varios monitores, elige el que quieras usar para el juego."
 SETTING_GRAPHICS_DEVICE:0 "Tarjeta gráfica"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Selecciona la tarjeta gráfica que usará el juego. \n\nSi utilizas una tarjeta gráfica integrada o un renderizador de software el rendimiento puede ser menor."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Calidad de sombras"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina la resolución con la que se reproducen las sombras en el mapa si están habilitadas.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_DISPLAY_MODE:0 "Modo de visualización"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Muestra cómo se mostrará el juego en tu pantalla"
 SETTING_BLOOM:0 "Luminosidad"
 SETTING_MESH_LOD_BIAS:0 "Calidad del nivel de detalle de malla"
 SETTING_MESH_LOD_FADE:0 "Difuminación de nivel de detalle de malla"
 SETTING_TERRAIN_SMOOTHING:1 "Suavizado de terreno"
 OPTION_FULLSCREEN:0 "Pantalla completa"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Se muestra el juego a pantalla completa. La nitidez de la imagen dependerá de la resolución."
 OPTION_WINDOWED:0 "Ventana"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Muestra el juego en una ventana. El tamaño de la ventana se ajustará a la resolución."
 OPTION_DISABLED:1 "Desactivado"
 OPTION_OFF:0 "No"
 OPTION_LOW:0 "Baja"
 OPTION_MEDIUM:0 "Media"
 OPTION_HIGH:0 "Alta"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Personalizada"
 OPTION_DEFAULT:1 "Predeterminado"
 SETTINGS_CATEGORY_UI:0 "Interfaz"
 SETTINGS_CATEGORY_GAME:0 "Partida"
 SETTING_TEXTURE_QUALITY:1 "Calidad de texturas"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nControla la resolución de las texturas que se cargan.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_QUALITY:0 "Preajuste de calidad"
 SETTING_SFX:0 "Efectos"
 SETTING_UI:0 "Interfaz"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Selecciona uno de los ajustes predeterminados para las opciones gráficas avanzadas que se muestran.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Activa el efecto "Luminosidad", de modo que las luces más intensas iluminarán otras partes de la imagen.\n\nDesactivarlo puede aumentar el rendimiento."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Activa la profundidad de campo para simular el objetivo de una cámara, difumina los puntos desenfocados de la imagen.\n\nDesactivarlo puede aumentar el rendimiento."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Determina si debe aplicarse al mapa la oclusión ambiental de espacio en pantalla.\n\nDesactivarlo puede mejorar el rendimiento."
 SETTING_REFRACTION_TOOLTIP:0 "Determina si aparecen o no reflejos en el agua."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nControla la calidad de los reflejos en el si está habilitado.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina el nivel de calidad más alto de los objetos del mapa (como edificios).\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina la calidad de los niveles de detalle de los objetos del mapa, como las unidades.\n\nUn ajuste inferior puede mejorar el rendimiento."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Al activarse, los modelos 3D tienen una transición más suave entre los diferentes niveles de detalle, al acercarse o alejarse de ellos.\n\nDesactivarlo puede mejorar el rendimiento."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Determina cómo aparecen los nombres de las ciudades y provincias en el mapa."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Determina si el terreno infranqueable se incluye dentro de las fronteras de una nación en el mapa."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nDetermina el idioma de la interfaz de usuario."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Tu cuenta de correo de Paradox"
 SETTING_FRAMERATE_CAP:1 "FPS máximo"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nMáximo de fotogramas por segundo (FPS) que mostrará el juego\n\nUn ajuste inferior puede mejorar el rendimiento."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "Transmisión de texturas"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\n\nLas texturas se cargan según se necesitan.\n\nReduce el uso de memoria de la GPU a cambio de cierta sobrecarga de la CPU. Puede mejorar el rendimiento de GPU con poca memoria."
 SETTING_TEXTURE_STREAMING_CACHE:0 "Tamaño de caché de transmisión de texturas"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Velocidad de animación"
 SETTING_GUI_SCALING:0 "Escala interfaz"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Ajusta la escala de la interfaz de usuario. Útil para resoluciones de pantalla altas.\n\n#X ¡Un nivel muy alto hará que las interfaces no encajen en la pantalla!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Desplazamiento ratón"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Libre"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 direcciones"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Desactivado"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nCómo se comporta la cámara cuando desplazamos el ratón."
 SETTING_SCROLL_SPEED:1 "Velocidad de desplazamiento"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nRapidez de desplazamiento por el mapa al usar el teclado o ratón."
 SETTING_CAMERA_ROTATION_SPEED:1 "Velocidad de rotación de cámara"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nLa velocidad de rotación de la cámara."
 SETTING_ZOOM_SPEED:1 "Velocidad de zoom"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nLa velocidad de zoom de la cámara."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Comportamiento del zoom"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Relativo al cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Zoom al cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ignorar cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nCómo actúa la cámara con respecto al cursor al acercarse y alejarse."
 SETTING_INPUT_DEVICE:0 "Dispositivo de entrada"
 SETTING_EDITOR:0 "Editor"
 SETTING_EDITOR_POSTFIX:0 "Editor Postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Comando de apertura del editor"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Ver registro de comandos"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Comando de apertura del editor de código"
 SETTING_GRACEFUL_EXIT:0 "Salida suave"
 SETTING_LANGUAGE:0 "Idioma"
 MOUSE_AND_KEYBOARD:0 "Ratón y teclado"
 GAMEPAD:0 "Mando de juego"
 SETTING_MULTISAMPLING_DISABLED:0 "Desactivado"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Desactivado"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Desactivado"
 # Editor
 SETTING_CAMERA_TILT:0 "Inclinación de cámara"
 SETTING_CAMERA_STRATEGY:0 "Tipo de cámara"
 SETTING_CENTERED_ZOOM_IN:0 "Zoom centrado"
 SETTING_CAMERA_SPEED:0 "Velocidad de cámara"
 CAMERA_TABLETOP:0 "Vista cenital"
 CAMERA_FPS:0 "Primera persona"
 CAMERA_WASD:0 "Estilo WASD"
 # Audio
 SETTING_Music:0 "Música"
 SETTING_Ambient:0 "Ambiente"
 SETTING_Effects:0 "Efectos"
 SETTING_Master:0 "General"
 SETTING_Master_TOOLTIP:0 "#T Volumen principal\n#!Controla el volumen de todos los sonidos del juego."
 SETTING_Music_TOOLTIP:0 "#T Volumen de la música\n#!Controla el volumen de la música de fondo."
 SETTING_Ambient_TOOLTIP:0 "#T Volumen ambiental\n#!Controla el volumen del ambiente."
 SETTING_SFX_TOOLTIP:0 "#T Volumen de los efectos\n#!Controla el volumen de los efectos de sonido, como el combate."
 SETTING_UI_TOOLTIP:0 "#T Volumen de la interfaz\n#!Controla el volumen de la interfaz de usuario."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Nivel de registro de depuración"
 SETTING_AUDIO_DEVICE_PROFILE:0 "Perfil de sonido"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Elige el perfil de sonido que se adapte a tu configuración."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Altavoces"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Mezcla predeterminada para $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Auriculares"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mezcla ajustada para $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV:0 "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Mezcla para altavoces de $SETTING_AUDIO_OPTION_TV$ y monitor."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Modo Noche"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Suaviza el sonido para jugar por la noche. Los tonos más altos quedan atenuados y se comprime el rango dinámico."
 SETTING_MUSIC_DENSITY:0 "Densidad de la música"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "Controla el equilibrio entre canciones completas, silencio y partes con música ambiental.\n\nIntensa: se reproducen principalmente canciones una detrás de otra. Es como una emisora de radio.\nEquilibrada: equilibrio perfecto entre canciones, silencio y música ambiental.\nRelajada: se reproduce principalmente música ambiental, que proporciona una experiencia más relajada. También reduce la sensación de fatiga por repetición tras varias horas de juego."
  # Game
 SETTING_AUTOSAVE:0 "Intervalo de autoguardado"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Controla la frecuencia con que el juego guarda automáticamente."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Determina si las partidas se guardan en la nube o no."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Determina si la cámara siempre está orientada hacia el norte o no."
 NO_AUTOSAVE:0 "Sin autoguardado"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "Velocidad de transferencia de archivos"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $File Transfer Speed$\n#!Controla la velocidad máxima para la transferencia de partidas guardadas en la sala multijugador.\n\nUna resolución inferior puede mejorar la estabilidad de la red para las partidas multijugador, pero tendrá un efecto negativo en los tiempos de carga."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Autoguardado editor de mapa (minutos)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Intervalo de autoguardado del editor de mapa (minutos)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Modo de desplazamiento del editor de nodos"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Accesibilidad"
 SETTING_COLOR_BLIND_MODE:0 "Modo daltonismo"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Cambia los colores empleados en el texto del juego a un conjunto de colores que sean más fáciles de distinguir para distintos tipos de daltonismo."

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 SETTING_MOUSE_PANNING:0 "Barrido de mouse"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!Decide si el mapa debería moverse si el cursor del mouse está al borde de la pantalla o ventana."
