l_simp_chinese:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$秒"
 SETTING_VALUE_MINUTES:0 "$VALUE$分钟"
 # Graphics
 SETTING_RENDERER:0 "渲染器"
 SETTING_RENDERER_TOOLTIP:0 "决定使用哪种渲染器。"
 SETTING_VSYNC:0 "垂直同步"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!使游戏的帧率与显示器的刷新率同步。\n\n关闭此选项可能会提升性能。"
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "肖像对重采样"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!使用多重采样Alpha-To-Coverage（A2C）使得头发丝的混合更加柔顺。\n\n降低设置可能会提高性能。"
 SETTING_MULTI_SAMPLING:0 "抗锯齿（MSAA）"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!采用多重采样抗锯齿（MSAA）能够使图像边缘更加平滑。\n\n降低设置可能会提高性能。"
 SETTING_ANTI_ALIASING:0 "抗锯齿"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!采用抗锯齿能够使得图像边缘变的更加平滑。\n\n推荐使用FXAA"
 OPTION_ANTI_ALIASING_DISABLED:0 "已禁用"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "材质过滤"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!采用各向异性过滤能够使贴图表面表现更佳。\n\n降低设置可能会提高性能。"
 SETTING_FULLSCREEN_RESOLUTION:0 "分辨率"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$#!\n设定游戏的图像质量。\n\n降低分辨率会提高性能。\n\n#X 使用不受支持的纵横比的分辨率可能会导致界面超出屏幕#!"
 SETTING_WINDOWED_RESOLUTION:0 "窗口化分辨率"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$#!\n设置当游戏在窗口模式下运行时使用的分辨率。\n\n格式必须为#b 数字#!x#b 数字#!。\n\n#X 设置的分辨率如果是游戏不支持的屏幕长宽比，将会导致界面溢出屏幕#!"
 SETTING_RENDER_SCALE:0 "渲染比例"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\n除开用户界面，游戏的渲染分辨率相对于主分辨率的比例。\n\n较低的设置可能会提高性能并降低整体的精确度，超过100%则会提高精确度但降低性能。"
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "显示器"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!如果你的电脑有多个显示器，选择游戏要使用哪一个。"
 SETTING_GRAPHICS_DEVICE:0 "显卡"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!选择游戏使用的显卡。\n\n使用集成显卡或者软件渲染器会降低性能。"
 SETTING_SHADOW_MAP_RESOLUTION:0 "阴影质量"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!开启阴影时，决定阴影贴图渲染的分辨率。\n\n降低设置可能会提高性能。"
 SETTING_DISPLAY_MODE:0 "显示模式"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!选择你需要的显示模式"
 SETTING_BLOOM:0 "泛光"
 SETTING_MESH_LOD_BIAS:0 "网格多层次细节质量"
 SETTING_MESH_LOD_FADE:0 "网格多层次细节渐变"
 SETTING_TERRAIN_SMOOTHING:1 "地形平滑"
 OPTION_FULLSCREEN:0 "全屏"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!以全屏模式显示游戏，分辨率设置将会更改整体的图像清晰度。"
 OPTION_WINDOWED:0 "窗口"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!以窗口模式显示游戏，分辨率设置将会更改窗口的大小。"
 OPTION_DISABLED:1 "已禁用"
 OPTION_OFF:0 "关闭"
 OPTION_LOW:0 "低"
 OPTION_MEDIUM:0 "中"
 OPTION_HIGH:0 "高"
 OPTION_ULTRA:1 "极致"
 OPTION_CUSTOM:0 "自定义"
 OPTION_DEFAULT:1 "默认"
 SETTINGS_CATEGORY_UI:0 "界面"
 SETTINGS_CATEGORY_GAME:0 "游戏"
 SETTING_TEXTURE_QUALITY:1 "材质质量"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\n控制已加载材质的分辨率。\n\n降低设置可能会提高性能。"
 SETTING_QUALITY:0 "质量预设"
 SETTING_SFX:0 "特效"
 SETTING_UI:0 "界面"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!从以下选择一个预设的高级图像选项。\n\n较低的预设能提升性能。"
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!启用“光晕”效果，图像中的高光部分将会溢出到图像的其他部分上。\n\n将其关闭可能会提高性能。"
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!启用景深以模拟相机镜头，模糊图像的失焦点。\n\n关闭此项可能会提升性能。"
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!决定屏幕空间的环境闭锁是否应用到地图。\n\n关闭可能提升性能"
 SETTING_REFRACTION_TOOLTIP:0 "决定水面上是否出现折射。"
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\n如果启用水面折射，控制水面折射的质量。\n\n降低设置可能会提高性能。"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\n决定地图物件（如建筑物）的最高质量等级。\n\n降低设置可能会提高性能。"
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\n决定地图物件（如单位模型）的多层次细节（细节级别）的质量。\n\n降低设置可能会提高性能。"
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!启用后，三维模型会在视角距离更改时，在不同等级的细节度（LOD）之间平滑转变。\n\n关闭此项可能会提升性能。"
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "决定城市和省份名字如何显示。"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "决定地图上某个国家的边界内是否包含无法通行的地形。"
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\n决定用户界面所用的语言。"
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "你的Paradox账号电子邮箱"
 SETTING_FRAMERATE_CAP:1 "帧数上限"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\n游戏最大帧数。\n\n降低该设置可以减少能耗。"
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "纹理流"
 SETTING_TEXTURE_STREAMING_CACHE:0 "纹理流缓存大小"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED:0 "动画速度"
 SETTING_GUI_SCALING:0 "图形用户界面缩放比例"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!设置整个用户界面的缩放比例。对于高分辨率屏幕有用。\n\n#X 设置过高可能会使得界面无法适配进入屏幕！#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "鼠标平移"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "自由"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "八向移动"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "已禁用"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\n当用鼠标平移时视角如何变化。"
 SETTING_SCROLL_SPEED:1 "平移速度"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\n当使用键盘或者鼠标时，设置地图平移有多快。"
 SETTING_CAMERA_ROTATION_SPEED:1 "视角旋转速度"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\n视角旋转的速度。"
 SETTING_ZOOM_SPEED:1 "缩放速度"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\n视角缩放的速度。"
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "缩放行为"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "相对光标"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "朝光标放大"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "忽略光标"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\n当缩放时，视角相对光标的运动行为。"
 SETTING_INPUT_DEVICE:0 "输入设备"
 SETTING_EDITOR:0 "编辑器"
 SETTING_EDITOR_POSTFIX:0 "编辑器后缀"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "编辑器开启指令"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "查看日志指令"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "代码编辑器开启指令"
 SETTING_GRACEFUL_EXIT:0 "平稳退出"
 SETTING_LANGUAGE:0 "语言"
 MOUSE_AND_KEYBOARD:0 "鼠标和键盘"
 GAMEPAD:0 "手柄"
 SETTING_MULTISAMPLING_DISABLED:0 "禁用"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "禁用"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "禁用"
 # Editor
 SETTING_CAMERA_TILT:0 "视角倾斜"
 SETTING_CAMERA_STRATEGY:0 "视角类型"
 SETTING_CENTERED_ZOOM_IN:0 "中心放大"
 SETTING_CAMERA_SPEED:0 "视角速度"
 CAMERA_TABLETOP:0 "桌面顶部"
 CAMERA_FPS:0 "第一人称"
 CAMERA_WASD:0 "WASD风格"
 # Audio
 SETTING_Music:0 "音乐"
 SETTING_Ambient:0 "周边环境"
 SETTING_Effects:0 "效果"
 SETTING_Master:0 "主要"
 SETTING_Master_TOOLTIP:0 "#T 主音量#!\n设定游戏内所有声音的音量。"
 SETTING_Music_TOOLTIP:0 "#T 音乐音量#!\n设定音乐的音量。"
 SETTING_Ambient_TOOLTIP:0 "#T 环境音量\n#!设置周边环境音效的音量。"
 SETTING_SFX_TOOLTIP:0 "#T 特效音量\n#!设置声音效果的音量，如战斗。"
 SETTING_UI_TOOLTIP:0 "#T 界面音量\n#!设置用户界面的音量。"
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Debug日志等级"
 SETTING_AUDIO_DEVICE_PROFILE:0 "音频配置"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$#!\n选择符合你的设置的音频配置。"
 SETTING_AUDIO_OPTION_SPEAKERS:0 "扬声器"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!$SETTING_AUDIO_OPTION_SPEAKERS$默认混响。"
 SETTING_AUDIO_OPTION_HEADPHONES:0 "耳机"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!为$SETTING_AUDIO_OPTION_HEADPHONES$调整的混响。"
 SETTING_AUDIO_OPTION_TV:0 "电视"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!为$SETTING_AUDIO_OPTION_TV$以及显示器扬声器调整的混响。"
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "夜间模式"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!柔化夜间游戏的声音，抑制高音并压缩动态范围。"
 SETTING_MUSIC_DENSITY:0 "音乐密度"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "控制完整曲目，静音和气氛音乐片段之间的平衡。\n\n激烈=类似于广播电台，主要一首接一首地播放完整曲目\n平衡=曲目、静音和气氛音乐片段之间的完美平衡\n舒缓=主要播放气氛音乐片段，为数小时的游玩后提供更平静的体验和更少的重复感。"
  # Game
 SETTING_AUTOSAVE:0 "自动保存间隔"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!设定游戏自动保存的频率。"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "决定是否将自动存档保存到云端。"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "决定视角是否始终朝北。"
 NO_AUTOSAVE:0 "禁用自动存档"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "文件传输速度"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T 文件传输速度\n#!设置多人游戏大厅里存档文件传输时的最大速度。\n\n降低设置可能会改善加入多人游戏时的网络稳定程度，但对于多人游戏的载入时间会产生负面效果。"
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "地图编辑器自动保存（分钟）"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "地图编辑器自动保存间隔（分钟）"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "节点编辑器拖动模式"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "可访问性"
 SETTING_COLOR_BLIND_MODE:0 "色盲模式"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!将游戏文本使用的颜色更改为各类色盲人群更容易区分的一组颜色。"

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 SETTING_MOUSE_PANNING:0 "鼠标卷动"
 SETTING_MOUSE_PANNING_TOOLTIP:0 "#T $SETTING_MOUSE_PANNING$\n#!设置大地图是否可以通过鼠标移动到屏幕或窗口边缘滚动。"
