l_french:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ secondes"
 SETTING_VALUE_MINUTES: "$VALUE$ minutes"
 #Graphics
 SETTING_RENDERER: "Rendu"
 SETTING_RENDERER_TOOLTIP: "Détermine la méthode de rendu utilisée."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$#!\nSynchronise le taux de rafraîchissement du jeu avec celui du moniteur, permettant de réduire l'effet de déchirement de l'écran (« screen tearing »).\n\nLe désactiver peut améliorer les performances du jeu."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Portrait multi-échantillonnage"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Utilisation du multi-échantillon pour l'« Alpha-To-Coverage » afin de rendre le mélange des cheveux plus fluide.\n\nUn réglage plus bas augmente les performances."
 SETTING_MULTI_SAMPLING: "Multi-échantillonnage"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$#!\nL'anticrénelage multisampling (MSAA) adoucit les bords des images.\n\nUne valeur moins élevée accroît les performances du jeu."
 SETTING_ANTI_ALIASING: "Anticrénelage"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!L'anticrénelage rendra les bords des images plus lisses.\n\nFXAA est recommandé."
 OPTION_ANTI_ALIASING_DISABLED: "Désactivé"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Méthode d’upscaling"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nLes méthodes d’upscaling permettent d’obtenir une résolution d’affichage plus élevée grâce à des algorithmes d’upscaling. Cela peut améliorer les performances, mais aussi entraîner l’apparition d’artefacts visuels ou d’autres conséquences inattendues.\n\nLes méthodes d’upscaling disponibles peuvent dépendre de votre carte graphique."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Qualité de l’upscaling"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nFocalise la méthode d’upscaling de la meilleure qualité possible aux meilleures performances possible."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Qualité Ultra"
 OPTION_UPSCALE_QUALITY_QUALITY: "Qualité"
 OPTION_UPSCALE_QUALITY_BALANCED: "Équilibrée"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Performance"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Performance Ultra"
 SETTING_ANISOTROPIC_FILTERING: "Filtrage anisotrope"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$#!\nLe filtrage anisotrope améliore la qualité des textures de surface.\n\nUne valeur moins élevée peut accroître les performances du jeu."
 SETTING_RESOLUTION: "Résolution du plein écran"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$#!\nDéfinit la qualité de l'image.\n\nUne résolution plus basse peut accroître les performances du jeu.\n\n#X Une résolution de jeu avec un format d'image non pris en charge peut faire apparaître les interfaces en dehors de l'écran.#!"
 SETTING_WINDOWED_RESOLUTION: "Résolution du mode fenêtré"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Définit la résolution de la fenêtre de jeu si le jeu est en mode fenêtré.\n\nDoit être au format #b NOMBRE#!x#b NOMBRE#!.\n\n#X Une résolution de jeu avec un format d'image non pris en charge peut faire apparaître les interfaces en dehors de l'écran#!"
 SETTING_RENDER_SCALE: "Échelle de rendu"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nL'échelle de la résolution de rendu du jeu par rapport à la résolution principale, à l'exclusion de l'interface utilisateur.\n\nUn réglage plus bas peut augmenter les performances mais réduire la fidélité globale, tandis qu'un réglage plus élevé que 100 % peut augmenter la fidélité mais dégradera probablement les performances."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Affichage"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$#!\nSi l'ordinateur a plusieurs écrans, permet de sélectionner celui qui sera utilisé par le jeu."
 SETTING_GRAPHICS_DEVICE: "Carte graphique"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$#!\nPermet de sélectionner la carte graphique qui sera utilisée par le jeu.\n\nUtiliser une carte ou un logiciel de rendu graphique intégré peut réduire les performances."
 SETTING_SHADOW_MAP_RESOLUTION: "Textures d'ombre"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$#!\nSi l'ombrage est activé, définit la résolution du rendu des ombres.\n\nUne valeur moins élevée peut améliorer les performances."
 SETTING_DISPLAY_MODE: "Mode d'affichage"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$#!\nAffiche le jeu sur l'ensemble de l'écran."
 SETTING_BLOOM_QUALITY: "Flou lumineux"
 SETTING_MESH_LOD_BIAS: "Qualité de détail des mesh"
 SETTING_MESH_LOD_FADE: "Transition du niveau de détails des mesh"
 SETTING_TERRAIN_SMOOTHING: "Lissage du terrain"
 OPTION_FULLSCREEN: "Plein écran"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$#!\nLe jeu sera affiché sur tout l'écran."
 OPTION_WINDOWED: "Fenêtre"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$#!\nUne fenêtre avec bordures, dont la résolution sera définie par les paramètres de hauteur et de largeur de la fenêtre."
 OPTION_DISABLED: "Désactivé"
 OPTION_OFF: "Désactivé"
 OPTION_LOW: "Bas"
 OPTION_MEDIUM: "Moyen"
 OPTION_HIGH: "Haut"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Personnalisé"
 OPTION_DEFAULT: "Défaut"
 SETTINGS_CATEGORY_UI: "Interfaces"
 SETTINGS_CATEGORY_GAME: "Jeu"
 SETTING_TEXTURE_QUALITY: "Qualité des textures"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nContrôle la résolution des textures chargées.\n\nDes paramètres limités peuvent accroître les performances."
 SETTING_QUALITY: "Préréglages qualité"
 SETTING_SFX: "Effets sonores"
 SETTING_UI: "Interfaces"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$#!\nSélectionner un préréglage des options ci-dessous.\n\nUn préréglage moins élevé accroît les performances du jeu."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Active un effet de flou lumineux qui entraîne la répercussion de lumières extrêmement brillantes sur d’autres parties de l’image.\n\nUn réglage faible peut améliorer les performances."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Active la profondeur de champ pour simuler l'objectif d'un appareil photo, floute les zones hors focus de l'image.\n\nLe désactiver peut améliorer les performances."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Active les effets de halo qui apparaissent dans les zones les plus lumineuses. Le flou lumineux doit être activé pour apparaître. \n\nLe désactiver peut améliorer les performances."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Active les effets de halo secondaires qui apparaissent dans les zones les plus lumineuses. Le flou lumineux doit être activé pour apparaître. \n\nLe désactiver peut améliorer les performances."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Détermine si l'occlusion ambiante de l'espace à l'écran doit être appliquée à la carte.\n\nLe désactiver peut améliorer les performances."
 SETTING_REFRACTION_TOOLTIP: "Détermine si les reflets apparaissent ou non sur l'eau."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nContrôle la qualité des reflets sur l'eau si ceux-ci sont activés.\n\nUne valeur plus basse peut améliorer les performances du jeu."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nDétermine le meilleur niveau de qualité pour les objets affichés sur la carte, tels que les bâtiments.\n\nUn réglage plus faible peut augmenter les performances."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nDétermine le niveau de détail, et donc la qualité des objets affichés sur la carte, tels que les modèles d'unités.\n\nUn réglage plus faible peut augmenter les performances."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$#!\nEn cas d'activation, les modèles 3D passent fluidement d'un niveau de détail (LOD) à un autre en zoomant ou dézoomant.\n\nLa désactiver peut améliorer les performances du jeu."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Définit la façon dont les noms des cités et provinces sont affichés sur la carte."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Définit si, sur la carte, le terrain infranchissable est inclus au sein des frontières des pays limitrophes."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nChoix de la langue dans laquelle la partie sera jouée."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Adresse e-mail utilisée lors de la création du compte Paradox."
 SETTING_FRAMERATE_CAP: "Images par seconde max."
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nLe nombre maximum d'images par seconde (FPS) que le jeu affichera.\n\nUne valeur inférieure peut réduire la consommation d'énergie."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Flux de textures"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nLes textures sont chargées selon les besoins.\n\nRéduit l’utilisation de la mémoire du GPU au détriment du temps de CPU. Cela peut augmenter les performances des GPU disposant d’une petite quantité de mémoire."
 SETTING_TEXTURE_STREAMING_CACHE: "Taille du cache du flux de textures"
 SETTING_VALUE_MB: "$VALUE$ MB"
 #GUI
 SETTING_ANIMATION_SPEED: "Vitesse des animations"
 SETTING_GUI_SCALING: "Échelle des interfaces"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$#!\nPermet de contrôler l'échelle de l'ensemble des interfaces du jeu, ce qui est utile pour les écrans haute résolution.\n\n#X Définir une valeur trop importante peut empêcher les interfaces de s'afficher intégralement à l'écran.#!"
 SETTING_TOOLS_GUI_SCALING: "Échelle de l’interface Outils"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Permet de contrôler l’échelle de l’interface utilisateur Outils, ce qui est utile pour les écrans haute résolution.\n\n#X Définir une valeur trop importante peut empêcher les interfaces de s’afficher intégralement à l’écran.#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Panoramique de la souris"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Libre"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 directions"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Désactivé"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nComment la caméra se comporte lorsque vous effectuez un panoramique avec la souris."
 SETTING_SCROLL_SPEED: "Vitesse du panoramique"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nDéfinit la vitesse à laquelle la carte se déplace lorsque vous utilisez le clavier ou la souris."
 SETTING_CAMERA_ROTATION_SPEED: "Vitesse de rotation de la caméra"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nLa vitesse de rotation de la caméra."
 SETTING_ZOOM_SPEED: "Vitesse du zoom"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nLa vitesse de zoom de la caméra."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Comportement du zoom"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Curseur relatif"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Zoomer sur le curseur"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignorer le curseur"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nComment la caméra se comporte par rapport au curseur de la souris lors d'un zoom avant/arrière."
 SETTING_INPUT_DEVICE: "Contrôles"
 SETTING_EDITOR: "Éditeur"
 SETTING_EDITOR_POSTFIX: "Éditeur de postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Commandes de l'éditeur"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Afficher le journal"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Commande d'ouverture de l'éditeur de code"
 SETTING_GRACEFUL_EXIT: "Sortie"
 SETTING_LANGUAGE: "Langue"
 MOUSE_AND_KEYBOARD: "Souris et clavier"
 GAMEPAD: "Manette"
 SETTING_MULTISAMPLING_DISABLED: "Désactivé"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Désactivé"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Désactivé"
 #Editor
 SETTING_CAMERA_TILT: "Panoramique caméra"
 SETTING_CAMERA_STRATEGY: "Type de caméra"
 SETTING_CENTERED_ZOOM_IN: "Centrer sur le zoom"
 SETTING_CAMERA_SPEED: "Vitesse de la caméra"
 CAMERA_TABLETOP: "Jeu de plateau"
 CAMERA_FPS: "Première personne"
 CAMERA_WASD: "Type ZQSD"
 #Audio
 SETTING_Music: "Musiques"
 SETTING_Ambient: "Sons d'ambiance"
 SETTING_Effects: "Effets"
 SETTING_Master: "Volume principal"
 SETTING_VO: "Voix off"
 SETTING_VO_TOOLTIP: "#T Volume de la voix off\n#!Permet de régler le volume de la voix off dans le jeu."
 SETTING_Master_TOOLTIP: "Réglage du volume principal."
 SETTING_Music_TOOLTIP: "Réglage du volume de la musique en fond sonore."
 SETTING_Ambient_TOOLTIP: "Réglage du volume des sons d'ambiance produits par l'environnement."
 SETTING_SFX_TOOLTIP: "Réglage du volume des effets sonores, tels que ceux produits par les combats."
 SETTING_UI_TOOLTIP: "Réglage du volume des sons produits par les interfaces du jeu."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Niveau du journal de débogage"
 SETTING_AUDIO_DEVICE_PROFILE: "Profil audio"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Choisissez le profil audio qui correspond à votre configuration."
 SETTING_AUDIO_OPTION_SPEAKERS: "Haut-parleurs"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Mixage par défaut pour les haut-parleurs."
 SETTING_AUDIO_OPTION_HEADPHONES: "Casque"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mixage ajusté pour le casque."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mixage pour TV et haut-parleurs d'écran."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Mode nuit"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Adoucit le son pour les jeux de nuit en atténuant les aigus et en comprimant la gamme dynamique."
 SETTING_MUSIC_DENSITY: "Densité musicale"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Contrôle la proportion entre les chansons complètes, le silence et les petites musiques d’ambiance\n\nIntense : principalement des chansons complètes jouées les unes après les autres, comme une station de radio\nÉquilibrée : l’équilibre parfait entre les chansons, le silence et la musique d’ambiance\nDétendue : principalement des petites musiques reposantes qui procurent une meilleure ambiance et moins de sensation de répétition après plusieurs heures de jeu"
 #Game
 SETTING_AUTOSAVE: "Intervalle de sauvegarde automatique"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$#!\nContrôle la fréquence des sauvegardes automatiques du jeu."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Définit si les sauvegardes automatiques doivent être enregistrées sur le cloud."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Définit si la caméra doit toujours être dirigée vers le nord."
 NO_AUTOSAVE: "Aucune sauv. auto."
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Vitesse de transfert de fichiers"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $SETTINGS_FILE_TRANSFER_SPEED$#!\nDéfinit la vitesse maximale pour les transferts de fichiers de sauvegarde dans le lobby multijoueur.\n\nDes paramètres plus bas peuvent améliorer la stabilité du réseau pour rejoindre des parties multijoueurs mais ont un impact négatif sur leur temps de chargement."
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Sauv. auto. de l'éditeur de carte (minutes)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Intervalle de sauv. auto. de l'éditeur de carte (minutes)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Mode panorama de l'éditeur de nœud"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Accessibilité"
 SETTING_COLOR_BLIND_MODE: "Mode daltonien"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Modifie les couleurs utilisées dans le texte du jeu en un ensemble de couleurs plus faciles à distinguer pour différents types de daltonisme."
