l_braz_por:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ segundos"
 SETTING_VALUE_MINUTES:0 "$VALUE$ minutos"
 # Graphics
 SETTING_RENDERER:0 "Renderizador"
 SETTING_VSYNC:0 "VSync"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Faz o jogo e seu monitor terem a mesma taxa de quadros, reduzindo a quebra de tela.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Múltipla Amostra de Retrato"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Usar múltipla amostra para Alpha-To-Coverage para suavizar a composição dos cabelos.\n\nConfigurações mais baixas aumentam o desempenho."
 SETTING_MULTI_SAMPLING:0 "Antisserrilhamento (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Usar o antisserrilhamento de múltipla amostra (MSAA) tornará as bordas das imagens mais suaves.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_ANTI_ALIASING:0 "Antisserrilhamento"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Usar o antisserrilhamento tornará as bordas das imagens mais suaves.\n\nRecomenda-se FXAA."
 OPTION_ANTI_ALIASING_DISABLED:0 "Desativado"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtragem de Texturas"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Usar a filtragem anisotrópica melhorará a aparência de superfícies texturizadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_FULLSCREEN_RESOLUTION:0 "Resolução"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Define a qualidade das imagens do jogo.\n\nConfigurações mais baixas podem aumentar o desempenho.\n\n#X Uma resolução de jogo com proporções não suportadas pode fazer com que as interfaces apareçam fora da tela#!"
 SETTING_WINDOWED_RESOLUTION:0 "Resolução em Janela"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Define a resolução da janela do jogo se ele estiver no Modo de Janela.\n\nDeve estar no formato #b NÚMERO#!x#b NÚMERO#!.\n\n#X Uma resolução de jogo com proporções não suportadas pode fazer com que as interfaces apareçam fora da tela#!"
 SETTING_RENDER_SCALE:0 "Escala de Renderização"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nA escala da resolução de renderização do jogo relativa à resolução principal, exceto a interface do usuário.\n\nConfigurações mais baixas podem aumentar o desempenho, mas diminuirão a fidelidade geral, enquanto passar de 100% pode aumentar a fidelidade, mas provavelmente comprometerá o desempenho."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Se seu computador tem vários monitores, escolha qual será utilizado no jogo."
 SETTING_GRAPHICS_DEVICE:0 "Placa de Vídeo"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Seleciona qual placa de vídeo o jogo usará. \n\nUsar placa de vídeo integrada ou renderização por software pode diminuir o desempenho."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Qualidade das Sombras"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina a resolução na qual os mapas de sombras são renderizados, se as sombras estiverem ativadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_DISPLAY_MODE:0 "Modo de Exibição"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Determina como o jogo será exibido na tela"
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Qualidade do ND de Malha"
 SETTING_MESH_LOD_FADE:0 "Esmaecimento do ND de Malha"
 SETTING_TERRAIN_SMOOTHING:1 "Suavização de Terrenos"
 OPTION_FULLSCREEN:0 "Tela Cheia"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Exibe o jogo usando a tela inteira. A configuração de resolução mudará a nitidez da imagem."
 OPTION_WINDOWED:0 "Janela"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Exibe o jogo em uma janela. A configuração de resolução muda o tamanho da janela."
 OPTION_DISABLED:1 "Desativado"
 OPTION_OFF:0 "Desligado"
 OPTION_LOW:0 "Baixo"
 OPTION_MEDIUM:0 "Médio"
 OPTION_HIGH:0 "Alto"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Personalizado"
 OPTION_DEFAULT:1 "Padrão"
 SETTINGS_CATEGORY_UI:0 "Interface"
 SETTINGS_CATEGORY_GAME:0 "Jogo"
 SETTING_TEXTURE_QUALITY:1 "Qualidade das Texturas"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nControla a resolução das texturas carregadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_QUALITY:0 "Predefinição de Qualidade"
 SETTING_SFX:0 "Efeitos Sonoros"
 SETTING_UI:0 "Interface"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Selecione uma predefinição dentre as opções de gráficos avançados abaixo.\n\nUma predefinição baixa aumentará o desempenho."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Ativa um efeito de "bloom", que faz luzes extremamente brilhantes transbordarem para outras partes da imagem.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Ativa a profundidade de campo para simular as lentes de uma câmera e embaça os pontos fora de foco da imagem.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Determina se a oclusão de ambiente do espaço da tela deve ser aplicada ao mapa.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_REFRACTION_TOOLTIP:0 "Determina se as refrações aparecerão na água."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nSe for ativada, controla a qualidade das refrações da água.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina o nível de qualidade mais alto de Objetos do Mapa (como construções).\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina a qualidade dos NDs (níveis de detalhe) dos objetos do mapa, como modelos de unidades.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Se for ligado, a transição dos modelos 3D ocorre suavemente entre diferentes níveis de detalhe (NDs) ao aproximar ou afastar a câmera.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Determina como os nomes de cidades e províncias aparecem no mapa."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Determina se terrenos intransponíveis são incluídos no território de uma nação no mapa."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nDetermina o idioma da interface do usuário."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "E-mail da sua Conta Paradox"
 SETTING_FRAMERATE_CAP:1 "FPS Máximo"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nFPS (quadros por segundo) máximo que o jogo renderiza.\n\nConfigurações mais baixas podem diminuir o consumo de energia."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "Fluxo de Texturas"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nAs texturas são carregadas quando necessário.\n\nReduz o uso de memória da GPU ao custo de um aumento no tempo de processamento da CPU. Pode melhorar o desempenho de GPUs com pouca quantidade de memória."
 SETTING_TEXTURE_STREAMING_CACHE:0 "Tamanho de Cache do Fluxo de Texturas"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Velocidade das animações"
 SETTING_GUI_SCALING:0 "Escala de GUI"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Define a escala da interface do usuário inteira. Útil para resoluções mais altas de tela.\n\n#X Uma configuração muito alta fará com que as interfaces não se encaixem adequadamente dentro da tela!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Comando Pan do Mouse"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Livre"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 direções"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Desativado"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nComo a câmera se comporta ao usar o comando Pan do mouse."
 SETTING_SCROLL_SPEED:1 "Velocidade do Comando Pan"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nDefine a velocidade do comando Pan no mapa ao usar o teclado ou o mouse."
 SETTING_CAMERA_ROTATION_SPEED:1 "Velocidade de Rotação da Câmera"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nA velocidade de rotação da câmera."
 SETTING_ZOOM_SPEED:1 "Velocidade de Aproximação"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nA velocidade de aproximação da câmera."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Comportamento da Aproximação"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Cursor relativo"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Aproximar em direção ao cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ignorar cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nComo a câmera se comporta em relação ao cursor do mouse ao aproximar/afastar a câmera."
 SETTING_INPUT_DEVICE:0 "Entrada de dispositivos"
 SETTING_EDITOR:0 "Editor"
 SETTING_EDITOR_POSTFIX:0 "Postfix do editor"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Comando "abrir" do editor"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Comando "ver registro""
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Comando "abrir" do editor de códigos"
 SETTING_GRACEFUL_EXIT:0 "Saída graciosa"
 SETTING_LANGUAGE:0 "Idioma"
 MOUSE_AND_KEYBOARD:0 "Mouse e teclado"
 GAMEPAD:0 "Gamepad"
 SETTING_MULTISAMPLING_DISABLED:0 "Desativado"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Desativada"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Desativada"
 # Editor
 SETTING_CAMERA_TILT:0 "Inclinação da câmera"
 SETTING_CAMERA_STRATEGY:0 "Tipo de câmera"
 SETTING_CENTERED_ZOOM_IN:0 "Aproximação centralizada"
 SETTING_CAMERA_SPEED:0 "Velocidade da câmera"
 CAMERA_TABLETOP:0 "Tabuleiro"
 CAMERA_FPS:0 "Primeira pessoa"
 CAMERA_WASD:0 "Estilo WASD"
 # Audio
 SETTING_Music:0 "Música"
 SETTING_Ambient:0 "Ambiente"
 SETTING_Effects:0 "Efeitos"
 SETTING_Master:0 "Geral"
 SETTING_Master_TOOLTIP:0 "#T Volume Geral\n#!Define o volume de todos os sons do jogo."
 SETTING_Music_TOOLTIP:0 "#T Volume da Música\n#!Define o volume da música."
 SETTING_Ambient_TOOLTIP:0 "#T Volume do Ambiente\n#!Define o volume dos sons do ambiente."
 SETTING_SFX_TOOLTIP:0 "#T Volume dos Efeitos Sonoros\n#!Define o volume dos efeitos sonoros, como os de combate."
 SETTING_UI_TOOLTIP:0 "#T Volume da Interface\n#!Define o volume da interface do usuário."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Nível de Registro de Debug"
 SETTING_AUDIO_DEVICE_PROFILE:0 "Perfil de Áudio"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Escolha o perfil de áudio que se adequa à sua configuração."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Caixas de Som"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Mixagem padrão para $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Fones de Ouvido"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mixagem ajustada para $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV:0 "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Mixagem para $SETTING_AUDIO_OPTION_TV$ e caixas de som do monitor."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Modo Noturno"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Suaviza os sons para jogar à noite, diminuindo tons mais agudos e comprimindo o alcance dinâmico."
 SETTING_MUSIC_DENSITY:0 "Densidade Musical"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "Controla o equilíbrio entre músicas completas, silêncio e segmentos de música ambiente. \n\nIntensa = Em grande parte, músicas tocando em sequência, semelhante a uma ""estação de rádio"". \nEquilibrada = O equilíbrio perfeito entre músicas, silêncio e ambientação. \nRelaxada = Em grande parte, segmentos de música relaxante que oferecem uma melhor experiência de ambientação e uma menor sensação de repetição após muitas horas jogando."
  # Game
 SETTING_AUTOSAVE:0 "Intervalo de Salvamento Automático"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Define a frequência com que o jogo será salvo automaticamente."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Determina se os jogos são salvos automaticamente na nuvem."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Determina se a câmera sempre aponta para o norte."
 NO_AUTOSAVE:0 "Sem Salvamento Automático"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "Velocidade de Transferência de Arquivos"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $File Transfer Speed$\n#!Define a velocidade máxima para transferências de arquivos de jogos salvos no lobby de multijogador.\n\nConfigurações mais baixas podem melhorar a estabilidade da rede ao ingressar em partidas multijogador, mas têm um efeito negativo nos tempos de carregamento."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Salvamento Automático do Editor de Mapas (minutos)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Intervalo do Salvamento Automático do Editor de Mapas (minutos)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Modo Pan de Arrastar do Editor de Interseções"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Acessibilidade"
 SETTING_COLOR_BLIND_MODE:0 "Modo Daltônico"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Muda as cores usadas nos textos do jogo para um conjunto de cores mais fáceis de distinguir para diferentes tipos de daltonismo."
