l_korean:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X 비율을 $VALUE|%0$ 이상으로 설정하면 인터페이스가 화면 바깥으로 넘어갈 수 있습니다.#!"
 RECOMMENDED_GUI_SCALE: "비율을 $VALUE|%0$ 이상으로 설정하면 인터페이스가 화면 바깥으로 넘어갈 수 있습니다."
