l_braz_por:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ segundos"
 SETTING_VALUE_MINUTES: "$VALUE$ minutos"
 #Graphics
 SETTING_RENDERER: "Renderizador"
 SETTING_RENDERER_TOOLTIP: "Determina qual renderizador está sendo usado."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Faz o jogo e seu monitor terem a mesma taxa de quadros, reduzindo a quebra de tela.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Múltipla Amostra de Retrato"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Usar múltipla amostra para Alpha-To-Coverage para suavizar a composição dos cabelos.\n\nConfigurações mais baixas aumentam o desempenho."
 SETTING_MULTI_SAMPLING: "Antisserrilhamento (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Usar o antisserrilhamento de múltipla amostra (MSAA) tornará as bordas das imagens mais suaves.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_ANTI_ALIASING: "Antisserrilhamento"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Usar o antisserrilhamento tornará as bordas das imagens mais suaves.\n\nRecomenda-se FXAA."
 OPTION_ANTI_ALIASING_DISABLED: "Desativado"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Método de Upscaling"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nOs métodos de upscaling podem ser usados para obter uma resolução de exibição mais alta por meio do upsampling algorítmico. Isso pode melhorar o desempenho, mas resultar em artefatos visuais ou outros comportamentos inesperados.\n\nOs métodos de upscaling disponíveis podem depender da sua placa de vídeo."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Qualidade de Upscaling"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nDefine o foco do método de upscalling, visando a melhor qualidade ou o melhor desempenho."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Qualidade Ultra"
 OPTION_UPSCALE_QUALITY_QUALITY: "Qualidade"
 OPTION_UPSCALE_QUALITY_BALANCED: "Equilibrada"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Desempenho"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Desempenho Ultra"
 SETTING_ANISOTROPIC_FILTERING: "Filtragem de Texturas"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Usar a filtragem anisotrópica melhorará a aparência de superfícies texturizadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_RESOLUTION: "Resolução"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Define a qualidade das imagens do jogo.\n\nConfigurações mais baixas podem aumentar o desempenho.\n\n#X Uma resolução de jogo com proporções não suportadas pode fazer com que as interfaces apareçam fora da tela#!"
 SETTING_WINDOWED_RESOLUTION: "Resolução em Janela"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Define a resolução da janela do jogo se ele estiver no Modo de Janela.\n\nDeve estar no formato #b NÚMERO#!x#b NÚMERO#!.\n\n#X Uma resolução de jogo com proporções não suportadas pode fazer com que as interfaces apareçam fora da tela#!"
 SETTING_RENDER_SCALE: "Escala de Renderização"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nA escala da resolução de renderização do jogo relativa à resolução principal, exceto a interface do usuário.\n\nConfigurações mais baixas podem aumentar o desempenho, mas diminuirão a fidelidade geral, enquanto passar de 100% pode aumentar a fidelidade, mas provavelmente comprometerá o desempenho."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Se seu computador tem vários monitores, escolha qual será utilizado no jogo."
 SETTING_GRAPHICS_DEVICE: "Placa de Vídeo"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Seleciona qual placa de vídeo o jogo usará. \n\nUsar placa de vídeo integrada ou renderização por software pode diminuir o desempenho."
 SETTING_SHADOW_MAP_RESOLUTION: "Qualidade das Sombras"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina a resolução na qual os mapas de sombras são renderizados, se as sombras estiverem ativadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_DISPLAY_MODE: "Modo de Exibição"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Determina como o jogo será exibido na tela"
 SETTING_BLOOM_QUALITY: "Incandescência"
 SETTING_MESH_LOD_BIAS: "Qualidade do ND de Malha"
 SETTING_MESH_LOD_FADE: "Esmaecimento do ND de Malha"
 SETTING_TERRAIN_SMOOTHING: "Suavização de Terrenos"
 OPTION_FULLSCREEN: "Tela Cheia"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Exibe o jogo usando a tela inteira. A configuração de resolução mudará a nitidez da imagem."
 OPTION_WINDOWED: "Janela"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Exibe o jogo em uma janela. A configuração de resolução muda o tamanho da janela."
 OPTION_DISABLED: "Desativado"
 OPTION_OFF: "Desligado"
 OPTION_LOW: "Baixo"
 OPTION_MEDIUM: "Médio"
 OPTION_HIGH: "Alto"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Personalizado"
 OPTION_DEFAULT: "Padrão"
 SETTINGS_CATEGORY_UI: "Interface"
 SETTINGS_CATEGORY_GAME: "Jogo"
 SETTING_TEXTURE_QUALITY: "Qualidade das Texturas"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nControla a resolução das texturas carregadas.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_QUALITY: "Predefinição de Qualidade"
 SETTING_SFX: "Efeitos Sonoros"
 SETTING_UI: "Interface"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Selecione uma predefinição dentre as opções de gráficos avançados abaixo.\n\nUma predefinição baixa aumentará o desempenho."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Ativa um efeito de incandescência, que faz luzes muito brilhantes se espalharem para outras partes da imagem.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Ativa a profundidade de campo para simular as lentes de uma câmera e embaça os pontos fora de foco da imagem.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Ativa na lente um efeito de clarão que aparece em áreas com muita incandescência. A incandescência deve estar ativada para que esse efeito apareça. \n\nDesativar pode melhorar o desempenho."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Ativa na lente um efeito de clarão secundário que aparece em áreas com muita incandescência. A incandescência deve estar ativada para que esse efeito apareça. \n\nDesativar pode melhorar o desempenho."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Determina se a oclusão de ambiente do espaço da tela deve ser aplicada ao mapa.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_REFRACTION_TOOLTIP: "Determina se as refrações aparecerão na água."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nSe for ativada, controla a qualidade das refrações da água.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina o nível de qualidade mais alto de Objetos do Mapa (como construções).\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina a qualidade dos NDs (níveis de detalhe) dos objetos do mapa, como modelos de unidades.\n\nConfigurações mais baixas podem aumentar o desempenho."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Se for ligado, a transição dos modelos 3D ocorre suavemente entre diferentes níveis de detalhe (NDs) ao aproximar ou afastar a câmera.\n\nDesligar isso pode aumentar o desempenho."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Determina como os nomes de cidades e províncias aparecem no mapa."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Determina se terrenos intransponíveis são incluídos no território de uma nação no mapa."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nDetermina o idioma da interface do usuário."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "E-mail da sua Conta Paradox"
 SETTING_FRAMERATE_CAP: "FPS Máximo"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nFPS (quadros por segundo) máximo que o jogo renderiza.\n\nConfigurações mais baixas podem diminuir o consumo de energia."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Fluxo de Texturas"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nAs texturas são carregadas quando necessário.\n\nReduz o uso de memória da GPU ao custo de um aumento no tempo de processamento da CPU. Pode melhorar o desempenho de GPUs com pouca quantidade de memória."
 SETTING_TEXTURE_STREAMING_CACHE: "Tamanho de Cache do Fluxo de Texturas"
 SETTING_VALUE_MB: "$VALUE$ MB"
 #GUI
 SETTING_ANIMATION_SPEED: "Velocidade das animações"
 SETTING_GUI_SCALING: "Escala de GUI"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Define a escala da interface do usuário inteira. Útil para resoluções mais altas de tela.\n\n#X Uma configuração muito alta fará com que as interfaces não se encaixem adequadamente dentro da tela!#!"
 SETTING_TOOLS_GUI_SCALING: "Escala da GUI das Ferramentas"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Define a escala da interface do usuário das ferramentas. Útil para resoluções de tela mais altas.\n\n#X Se deixá-la muito alta, as interfaces não se encaixarão corretamente na tela!#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Comando Pan do Mouse"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Livre"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 direções"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Desativado"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nComo a câmera se comporta ao usar o comando Pan do mouse."
 SETTING_SCROLL_SPEED: "Velocidade do Comando Pan"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nDefine a velocidade do comando Pan no mapa ao usar o teclado ou o mouse."
 SETTING_CAMERA_ROTATION_SPEED: "Velocidade de Rotação da Câmera"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nA velocidade de rotação da câmera."
 SETTING_ZOOM_SPEED: "Velocidade de Aproximação"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nA velocidade de aproximação da câmera."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Comportamento da Aproximação"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Cursor relativo"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Aproximar em direção ao cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignorar cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nComo a câmera se comporta em relação ao cursor do mouse ao aproximar/afastar a câmera."
 SETTING_INPUT_DEVICE: "Entrada de dispositivos"
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_POSTFIX: "Postfix do editor"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Comando \"abrir\" do editor"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Comando \"ver registro\""
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Comando \"abrir\" do editor de códigos"
 SETTING_GRACEFUL_EXIT: "Saída graciosa"
 SETTING_LANGUAGE: "Idioma"
 MOUSE_AND_KEYBOARD: "Mouse e teclado"
 GAMEPAD: "Gamepad"
 SETTING_MULTISAMPLING_DISABLED: "Desativado"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Desativada"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Desativada"
 #Editor
 SETTING_CAMERA_TILT: "Inclinação da câmera"
 SETTING_CAMERA_STRATEGY: "Tipo de câmera"
 SETTING_CENTERED_ZOOM_IN: "Aproximação centralizada"
 SETTING_CAMERA_SPEED: "Velocidade da câmera"
 CAMERA_TABLETOP: "Tabuleiro"
 CAMERA_FPS: "Primeira pessoa"
 CAMERA_WASD: "Estilo WASD"
 #Audio
 SETTING_Music: "Música"
 SETTING_Ambient: "Ambiente"
 SETTING_Effects: "Efeitos"
 SETTING_Master: "Geral"
 SETTING_VO: "Dublagem"
 SETTING_VO_TOOLTIP: "#T Volume da Dublagem\n#!Define o volume do áudio dublado no jogo."
 SETTING_Master_TOOLTIP: "#T Volume Geral\n#!Define o volume de todos os sons do jogo."
 SETTING_Music_TOOLTIP: "#T Volume da Música\n#!Define o volume da música."
 SETTING_Ambient_TOOLTIP: "#T Volume do Ambiente\n#!Define o volume dos sons do ambiente."
 SETTING_SFX_TOOLTIP: "#T Volume dos Efeitos Sonoros\n#!Define o volume dos efeitos sonoros, como os de combate."
 SETTING_UI_TOOLTIP: "#T Volume da Interface\n#!Define o volume da interface do usuário."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Nível de Registro de Debug"
 SETTING_AUDIO_DEVICE_PROFILE: "Perfil de Áudio"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Escolha o perfil de áudio que se adequa à sua configuração."
 SETTING_AUDIO_OPTION_SPEAKERS: "Caixas de Som"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Mixagem padrão para $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Fones de Ouvido"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mixagem ajustada para $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mixagem para $SETTING_AUDIO_OPTION_TV$ e caixas de som do monitor."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Modo Noturno"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Suaviza os sons para jogar à noite, diminuindo tons mais agudos e comprimindo o alcance dinâmico."
 SETTING_MUSIC_DENSITY: "Densidade Musical"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Controla o equilíbrio entre músicas completas, silêncio e segmentos de música ambiente. \n\nIntensa = Em grande parte, músicas tocando em sequência, semelhante a uma \"\"estação de rádio\"\". \nEquilibrada = O equilíbrio perfeito entre músicas, silêncio e ambientação. \nRelaxada = Em grande parte, segmentos de música relaxante que oferecem uma melhor experiência de ambientação e uma menor sensação de repetição após muitas horas jogando."
 #Game
 SETTING_AUTOSAVE: "Intervalo de Salvamento Automático"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Define a frequência com que o jogo será salvo automaticamente."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Determina se os jogos são salvos automaticamente na nuvem."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Determina se a câmera sempre aponta para o norte."
 NO_AUTOSAVE: "Sem Salvamento Automático"
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Velocidade de Transferência de Arquivos"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Define a velocidade máxima para transferências de arquivos de jogos salvos no lobby de multijogador.\n\nConfigurações mais baixas podem melhorar a estabilidade da rede ao ingressar em partidas multijogador, mas têm um efeito negativo nos tempos de carregamento."
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Salvamento Automático do Editor de Mapas (minutos)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Intervalo do Salvamento Automático do Editor de Mapas (minutos)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Modo Pan de Arrastar do Editor de Interseções"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Acessibilidade"
 SETTING_COLOR_BLIND_MODE: "Modo Daltônico"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Muda as cores usadas nos textos do jogo para um conjunto de cores mais fáceis de distinguir para diferentes tipos de daltonismo."
