l_turkish:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ saniye"
 SETTING_VALUE_MINUTES: "$VALUE$ dakika"
 #Graphics
 SETTING_RENDERER: "İşleyici"
 SETTING_RENDERER_TOOLTIP: "Hangi işleyicinin kullanıldığını belirler."
 SETTING_VSYNC: "Dikey Eşitleme"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Oyunla monitörünün aynı kare hızına sahip olmasını sağlayarak ekran yırtılmalarını azaltır.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Portre Çoklu Örnekleme"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Alpha-To-Coverage yöntemi için çoklu örnekleme kullanarak saçları daha yumuşak hale getirir.\n\nBu ayarın düşürülmesi performansı arttırır."
 SETTING_MULTI_SAMPLING: "Kenar Yumuşatma (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!MSAA (çoklu örneklemeli kenar yumuşatma) tekniğini kullanarak görüntülerin kenarlarını daha pürüzsüz hale getirir.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_ANTI_ALIASING: "Kenar Yumuşatma"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Görüntülerin kenarlarını daha pürüzsüz hale getirir.\n\nFXAA önerilir."
 OPTION_ANTI_ALIASING_DISABLED: "Kapalı"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Yukarı Ölçekleme Yöntemi"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nYukarı ölçekleme yöntemleri, algoritmik yukarı örnekleme yoluyla daha yüksek ekran çözünürlüğü elde etmek için kullanılabilir. Bu, performansı arttırabilir ancak görsel bozulmalara veya diğer beklenmedik durumlara neden olabilir.\n\nKullanılabilen yukarı ölçekleme yöntemleri, mevcut grafik kartına bağlıdır."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Yukarı Ölçekleme Kalitesi"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nYukarı ölçekleme yönteminin odağını en yüksek kaliteyi hedeflemek ile en yüksek performansı hedeflemek arasında ayarlar."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra Kalite"
 OPTION_UPSCALE_QUALITY_QUALITY: "Kalite"
 OPTION_UPSCALE_QUALITY_BALANCED: "Dengeli"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Performans"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Ultra Performans"
 SETTING_ANISOTROPIC_FILTERING: "Doku Filtreleme"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Eşyönsüz filtreleme dokulu yüzeylerin daha iyi görünmesini sağlar.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_RESOLUTION: "Çözünürlük"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Oyunun görüntü kalitesini belirler.\n\nÇözünürlüğün düşürülmesi performansı arttırabilir.\n\n#X Desteklenmeyen görüntü oranlarını gerektiren çözünürlükler, arayüzlerin ekranın dışına taşmasına sebep olabilir.#!"
 SETTING_WINDOWED_RESOLUTION: "Pencere Çözünürlüğü"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Oyunun pencereli modda çalışması halinde oyun penceresinin çözünürlüğünü belirler.\n\n#b SAYI#!x#b SAYI#! formatında olmalıdır.\n\n#X Desteklenmeyen görüntü oranlarını gerektiren çözünürlükler, arayüzlerin ekranın dışına taşmasına sebep olabilir.#!"
 SETTING_RENDER_SCALE: "İşleme Ölçeği"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nOyunun işlendiği çözünürlüğün ana çözünürlüğe oranı. Kullanıcı arayüzünün çözünürlüğü buna dahil değildir.\n\nBu ayarın düşürülmesi performansı arttırabilir fakat genel görüntü kalitesini düşürür. Öte yandan bu ayarın %100'ün üzerine çıkarılması görüntü kalitesini arttırabilir fakat performansı düşürebilir."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitör"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Birden çok monitörün varsa oyunun kullanacağı monitörü buradan seçebilirsin."
 SETTING_GRAPHICS_DEVICE: "Ekran Kartı"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Oyunun kullanacağı ekran kartı.\n\nTümleşik bir ekran kartı ya da yazılım işleyici kullanmak oyun performansını düşürebilir."
 SETTING_SHADOW_MAP_RESOLUTION: "Gölge Kalitesi"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Gölgelerin devrede olması halinde gölge haritalamasının çizim çözünürlüğünü belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_DISPLAY_MODE: "Görüntü Modu"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Oyunun ekranda nasıl görüntüleneceğini belirler."
 SETTING_BLOOM_QUALITY: "Parlama"
 SETTING_MESH_LOD_BIAS: "Model Ayrıntı Düzeyi Kalitesi"
 SETTING_MESH_LOD_FADE: "Model Ayrıntı Düzeyi Azalması"
 SETTING_TERRAIN_SMOOTHING: "Arazi Pürüzsüzleştirme"
 OPTION_FULLSCREEN: "Tam Ekran"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Oyunu ekranın tamamını kullanarak görüntüle. Çözünürlük ayarı, görüntünün netliğini değiştirir."
 OPTION_WINDOWED: "Pencere"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Oyunu bir pencerede görüntüle. Çözünürlük ayarı, pencerenin boyutunu değiştirir."
 OPTION_DISABLED: "Kapalı"
 OPTION_OFF: "Kapalı"
 OPTION_LOW: "Düşük"
 OPTION_MEDIUM: "Orta"
 OPTION_HIGH: "Yüksek"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Özel"
 OPTION_DEFAULT: "Varsayılan"
 SETTINGS_CATEGORY_UI: "Arayüz"
 SETTINGS_CATEGORY_GAME: "Oyun"
 SETTING_TEXTURE_QUALITY: "Doku Kalitesi"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nYüklenen dokuların çözünürlüğünü belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_QUALITY: "Kalite Ön Ayarı"
 SETTING_SFX: "Özel Efektler"
 SETTING_UI: "Arayüz"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Gelişmiş grafik seçenekleri için aşağıdan bir ön ayar seç.\n\nDüşük bir ön ayar performansı arttırır."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Fazlasıyla parlak ışıkların görselin diğer bölümlerine de taşmasını sağlayan bir \"parlama\" efektini etkinleştirir.\n\nDüşük ayarlar performansı arttırır."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Bir kamera lensini simüle etmek için alan derinliğini açar ve görüntüde odağın dışında kalan yerleri bulanıklaştırır.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Yüksek derecede parlak görünen kısımlar için bir lens parlaması efektini etkinleştirir. Efektin görünmesi için Işık Parlamaları ayarı etkin olmalıdır. \n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Yüksek derecede parlak görünen kısımlar için ikinci bir lens parlaması efektini etkinleştirir. Efektin görünmesi için Işık Parlamaları ayarı etkin olmalıdır. \n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!SSAO (ekran alanı çevresel perdeleme) yönteminin haritaya uygulanıp uygulanmayacağını belirler.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_REFRACTION_TOOLTIP: "Suda ışık kırılmalarının oluşup oluşmayacağını belirler."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nAçık olması halinde suda oluşacak ışık kırılmalarının kalitesini belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nHaritadaki nesnelerin (binalar vb.) kalite düzeyini belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nHaritadaki nesnelerin (birim modelleri vb.) ayrıntı düzeyi kalitesini belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Bu ayar açıldığında, haritaya yakınlaştırma-uzaklaştırma yaparken 3D modellerin ayrıntı düzeyleri arasında pürüzsüz bir şekilde geçiş yapılır.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Şehir ve idari bölge adlarının haritada nasıl görüneceğini belirler."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Geçilmez arazilerin haritada ülkelerin sınırlarına dahil edilip edilmeyeceğini belirler."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nKullanıcı arayüzünün dilini belirler."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Paradox hesabın için kullandığın e-posta adresi"
 SETTING_FRAMERATE_CAP: "Maksimum FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nOyunun çalışacağı maksimum FPS (saniyelik kare hızı).\n\nBu ayarın düşürülmesi güç tüketimini azaltabilir."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Doku Akışı"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nDokular ihtiyaç oldukça yüklenir.\n\nİşlemciye bir miktar yük ekleyerek ekran kartının bellek kullanımını azaltır. Bellek boyutu düşük olan ekran kartlarında performansı arttırabilir."
 SETTING_TEXTURE_STREAMING_CACHE: "Doku Akışı Önbellek Boyutu"
 SETTING_VALUE_MB: "$VALUE$ MB"
 #GUI
 SETTING_ANIMATION_SPEED: "Animasyon hızı"
 SETTING_GUI_SCALING: "Grafiksel Kullanıcı Arayüzü (GUI) Ölçekleme"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Bütün kullanıcı arayüzlerinin ölçeğini belirler. Yüksek ekran çözünürlükleri için kullanışlı bir ayardır.\n\n#X Bu ayar fazla yükseltilirse arayüzler ekrana düzgün bir şekilde sığmaz!#!"
 SETTING_TOOLS_GUI_SCALING: "Araçlar Grafiksel Kullanıcı Arayüzü (GUI) Ölçeklemesi"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Araçlar kullanıcı arayüzünün boyutunu ayarlar. Yüksek ekran çözünürlüğü için kullanışlıdır.\n\n#X Çok yükseğe ayarlamak arayüzlerin ekrandan taşmasına sebep olur!#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Fare Kaydırması"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Serbest"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 yönlü"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Kapalı"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nFareyle ekranı kaydırırken kameranın nasıl davranacağını belirler."
 SETTING_SCROLL_SPEED: "Kaydırma Hızı"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nKlavye ya da fareyi kullanırken haritanın ne kadar hızlı kaydırılacağını belirler."
 SETTING_CAMERA_ROTATION_SPEED: "Kamera Dönüş Hızı"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nKameranın dönüş hızı."
 SETTING_ZOOM_SPEED: "Yakınlaştırma-Uzaklaştırma Hızı"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nKameranın yakınlaştırma-uzaklaştırma hızı."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Yakınlaştırma-Uzaklaştırma Davranışı"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Göreli imleç"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "İmlece yakınlaş"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "İmleci görmezden gel"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nYakınlaştırma-uzaklaştırma yaparken kameranın fare imlecine göre nasıl davranacağını belirler."
 SETTING_INPUT_DEVICE: "Giriş aygıtı"
 SETTING_EDITOR: "Editör"
 SETTING_EDITOR_POSTFIX: "Editör soneki"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Editör açma komutu"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Günlük komutunu göster"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Kod editörü açma komutu"
 SETTING_GRACEFUL_EXIT: "Kontrollü çıkış"
 SETTING_LANGUAGE: "Dil"
 MOUSE_AND_KEYBOARD: "Fare ve klavye"
 GAMEPAD: "Oyun kumandası"
 SETTING_MULTISAMPLING_DISABLED: "Kapalı"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Kapalı"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Kapalı"
 #Editor
 SETTING_CAMERA_TILT: "Kamera eğimi"
 SETTING_CAMERA_STRATEGY: "Kamera türü"
 SETTING_CENTERED_ZOOM_IN: "Ortalanmış yakınlaştırma"
 SETTING_CAMERA_SPEED: "Kamera hızı"
 CAMERA_TABLETOP: "Masa oyunu"
 CAMERA_FPS: "Birinci şahıs"
 CAMERA_WASD: "WASD tarzı"
 #Audio
 SETTING_Music: "Müzik"
 SETTING_Ambient: "Ortam"
 SETTING_Effects: "Efektler"
 SETTING_Master: "Ana Ses"
 SETTING_VO: "Seslendirme"
 SETTING_VO_TOOLTIP: "#T Seslendirme Ses Düzeyi\n#!Oyundaki seslendirmelerin ses düzeyini belirler."
 SETTING_Master_TOOLTIP: "#T Ana Ses Düzeyi\n#!Oyundaki tüm seslerin düzeyini belirler."
 SETTING_Music_TOOLTIP: "#T Müzik Düzeyi\n#!Çalan müziklerin ses düzeyini belirler."
 SETTING_Ambient_TOOLTIP: "#T Ortam Sesleri Düzeyi\n#!Çevresel ambiyans seslerinin düzeyini belirler."
 SETTING_SFX_TOOLTIP: "#T Ses Efekt Düzeyi\n#!Savaş vb. ses efektlerinin düzeyini belirler."
 SETTING_UI_TOOLTIP: "#T Arayüz Ses Düzeyi\n#!Kullanıcı arayüzünün ses düzeyini belirler."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Hata Ayıklama Günlüğü Düzeyi"
 SETTING_AUDIO_DEVICE_PROFILE: "Ses Profili"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Kurulumuna uygun bir ses profili seç."
 SETTING_AUDIO_OPTION_SPEAKERS: "Hoparlör"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!$SETTING_AUDIO_OPTION_SPEAKERS$ için varsayılan ses karıştırıcısı."
 SETTING_AUDIO_OPTION_HEADPHONES: "Kulaklık"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!$SETTING_AUDIO_OPTION_HEADPHONES$ için ayarlanan ses karıştırıcısı."
 SETTING_AUDIO_OPTION_TV: "Televizyon"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!$SETTING_AUDIO_OPTION_TV$ ve monitör hoparlörü için ayarlanan ses karıştırıcısı."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Gece Modu"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Gece oynanan oyunlar için tiz sesleri kısarak ve dinamik aralığı sıkıştırarak sesi yumuşatır."
 SETTING_MUSIC_DENSITY: "Densidad de la música"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Tam şarkılar, sessizlik ve duruma uygun müzik segmentleri arasındaki dengeyi kontrol eder.\n\nYoğun = Çoğunlukla bir radyo istasyonu gibi arka arkaya şarkılar çalınır.\nDengeli = Şarkılar, sessizlik ve duruma uygun müzikler arasında kusursuz bir denge kurulur.\nSakin = Çoğunlukla daha huzurlu bir ortam sunan ve tekrarlanma sıklığı daha düşük olan rahatlatıcı müzik segmentleri çalınır."
 #Game
 SETTING_AUTOSAVE: "Otomatik Kayıt Aralığı"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Oyunun hangi sıklıkta otomatik kayıt yapacağını belirler."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Otomatik kayıtların buluta kaydedilip kaydedilmeyeceğini belirler."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Kameranın kuzey yönüne kilitlenip kilitlenmeyeceğini belirler."
 NO_AUTOSAVE: "Otomatik Kaydı Kapat"
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Dosya Aktarım Hızı"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $Dosya Aktarım Hızı$\n#!Çok oyunculu lobide kayıt dosyalarının maksimum aktarım hızını belirler.\n\nBu ayarın düşürülmesi çok oyunculu oyunlara bağlanırken ağ istikrarını geliştirebilir ancak çok oyunculu yükleme sürelerine olumsuz etki eder."
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Harita Editöründe Otomatik Kayıt (dakika)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Harita Editörü Otomatik Kayıt Aralığı (dakika)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Nokta Editörü Sürükleme-Kaydırma Modu"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Erişilebilirlik"
 SETTING_COLOR_BLIND_MODE: "Renk Körü Modu"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Oyun metinlerinin rengini farklı renk körlüklerine göre değiştirerek metinlerin ayırt edilmesini kolaylaştırır."
