l_turkish:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X $VALUE|%0$ değerinin üstündeki ölçeklemeler, arayüzlerin ekranın dışına taşmasına sebep olur#!"
 RECOMMENDED_GUI_SCALE: "$VALUE|%0$ değerinin üstündeki ölçeklemeler, arayüzlerin ekranın dışına taşmasına sebep olur"
