l_russian:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ сек."
 SETTING_VALUE_MINUTES: "$VALUE$ мин."
 #Graphics
 SETTING_RENDERER: "Рендеринг"
 SETTING_RENDERER_TOOLTIP: "Определяет используемый рендерер."
 SETTING_VSYNC: "Вертикальная синхронизация"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Синхронизирует частоту кадров игры и монитора, уменьшая разрывы изображения на экране.\n\nОтключение этого параметра может повысить производительность."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Сглаживание портретов"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Использование сглаживания по технологии Alpha-To-Coverage для более плавного наложения волос.\n\nСнижение параметра может повысить производительность."
 SETTING_MULTI_SAMPLING: "Сглаживание (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!При использовании сглаживания с множественной выборкой (MSAA) края изображения становятся более гладкими.\n\nСнижение параметра может повысить производительность."
 SETTING_ANTI_ALIASING: "Сглаживание"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!При использовании сглаживания края изображения будут менее резкими.\n\nРекомендуем использовать FXAA."
 OPTION_ANTI_ALIASING_DISABLED: "Выкл."
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Метод масштабирования"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nМетоды масштабирования позволяют достичь более высокого разрешения с помощью алгоритмичной повышающей дискретизации. Это может повысить производительность, но существует риск возникновения артефактов и иного неожиданного поведения.\n\nДоступность методов масштабирования может зависеть от вашей графической карты."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Качество масштабирования"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nЗадаёт приоритет метода масштабирования от высокого качества до высокой производительности."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Высокое качество"
 OPTION_UPSCALE_QUALITY_QUALITY: "Качество"
 OPTION_UPSCALE_QUALITY_BALANCED: "Сбалансировано"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Производительность"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Высокая производительность"
 SETTING_ANISOTROPIC_FILTERING: "Фильтрация текстур"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Использование анизотропной фильтрации улучшает внешний вид текстурированных поверхностей.\n\nСнижение параметра может повысить производительность."
 SETTING_RESOLUTION: "Разрешение"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Качество изображения в игре.\n\nСнижение разрешения может повысить производительность.\n\n#X Разрешения с неподдерживаемым соотношением сторон могут привести к выходу элементов интерфейса за пределы экрана#!"
 SETTING_WINDOWED_RESOLUTION: "Разрешение в оконном режиме"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Если игра запущена в оконном режиме — определяет разрешение окна.\n\nНеобходимо использовать формат #b ЧИСЛО#!x#b ЧИСЛО#!.\n\n#X Разрешение с неподдерживаемым соотношением сторон может привести к тому, что интерфейс окажется за пределами экрана#!"
 SETTING_RENDER_SCALE: "Размер рендера"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nРазмер разрешения рендера в игре относительно разрешения экрана за вычетом интерфейса.\n\nСнижение параметра может повысить производительность, но понизит качество изображения, тогда как увеличение свыше 100% может повысить качество, но, вероятно, понизит производительность."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Монитор"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Если у вашего компьютера несколько мониторов, выберите тот, который будет использоваться в игре."
 SETTING_GRAPHICS_DEVICE: "Видеокарта"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Выберите, какая видеокарта будет использоваться в игре.\n\nИспользование интегрированной видеокарты или программного рендеринга может снизить производительность."
 SETTING_SHADOW_MAP_RESOLUTION: "Качество теней"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Если тени включены, параметр определяет разрешение, с которым накладываются карты теней.\n\nСнижение параметра может повысить производительность."
 SETTING_DISPLAY_MODE: "Режим отображения"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Определяет, как будет отображаться игра на вашем экране"
 SETTING_BLOOM_QUALITY: "Свечение"
 SETTING_MESH_LOD_BIAS: "Качество детализации сетки"
 SETTING_MESH_LOD_FADE: "Убывание детализации сетки"
 SETTING_TERRAIN_SMOOTHING: "Сглаживание ландшафта"
 OPTION_FULLSCREEN: "Полноэкранный"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Отображать игру во весь экран. Настройки расширения будут влиять на четкость изображения."
 OPTION_WINDOWED: "Оконный режим"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Отображать игру в окне. Настройки разрешения меняют размер окна."
 OPTION_DISABLED: "Выкл."
 OPTION_OFF: "Выкл."
 OPTION_LOW: "Низкий"
 OPTION_MEDIUM: "Средний"
 OPTION_HIGH: "Высокий"
 OPTION_ULTRA: "Очень высокий"
 OPTION_CUSTOM: "Пользовательский"
 OPTION_DEFAULT: "По умолчанию"
 SETTINGS_CATEGORY_UI: "Интерфейс"
 SETTINGS_CATEGORY_GAME: "Игра"
 SETTING_TEXTURE_QUALITY: "Качество текстур"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nРазрешение загруженных текстур.\n\nСнижение параметра может повысить производительность."
 SETTING_QUALITY: "Сохраненная настройка качества"
 SETTING_SFX: "Звуковые эффекты"
 SETTING_UI: "Интерфейс"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Выберите сохраненный параметр в дополнительных настройках графики внизу.\n\nНизкое значение сохраненного параметра повысит производительность."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Включает эффект свечения, благодаря которому источники особо яркого света будут освещать и другие части изображения.\n\nСнижение значения может повысить производительность."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Включает глубину поля, симулирующую объектив камеры, размывает части изображения, не находящиеся в фокусе.\n\nОтключение параметра может повысить производительность."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Включает эффект бликов, появляющийся в ярко освещённых местах. Чтобы эффект появился, необходимо включить свечение.\n\nОтключение параметра может повысить производительность."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Включает эффект вторичных бликов, появляющийся в ярко освещённых местах. Чтобы эффект появился, необходимо включить свечение.\n\nОтключение параметра может повысить производительность."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Определяет, будет ли применяться к карте преграждение окружающего света в экранном пространстве.\n\nОтключение параметра может повысить производительность."
 SETTING_REFRACTION_TOOLTIP: "Отображать (или нет) отражения на воде."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nКачество отражений на воде (если они отображаются).\n\nСнижение параметра может повысить производительность."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nМаксимальный уровень качества отображения объектов на карте (здания и т. п.).\n\nСнижение параметра может повысить производительность."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nКачество детализации объектов на карте (подразделения и т. п.).\n\nСнижение параметра может повысить производительность."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Если включен этот параметр, в трехмерных моделях происходит плавный переход между различными уровнями детализации при изменении масштаба.\n\nОтключение параметра может повысить производительность."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Способ показывать на карте названия городов и провинций."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Включать (или нет) в границы державы на карте непроходимые участки."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nЯзык пользовательского интерфейса."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Адрес вашей эл. почты для учетной записи Paradox"
 SETTING_FRAMERATE_CAP: "Ограничение числа кадров"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nОграничение числа кадров в секунду, которое будет отображать игра.\n\nСнижение параметра может сократить потребление электроэнергии."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Стриминг текстур"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nТекстуры подгружаются по мере необходимости.\n\nСнижает нагрузку на графический процессор, но увеличивает потребление ресурсов ЦПУ. Может повысить производительность графических карт с небольшим запасом памяти."
 SETTING_TEXTURE_STREAMING_CACHE: "Размер кэша стриминга текстур"
 SETTING_VALUE_MB: "$VALUE$ МБ"
 #GUI
 SETTING_ANIMATION_SPEED: "Скорость анимации"
 SETTING_GUI_SCALING: "Масштабирование интерфейса"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Задает масштаб пользовательского интерфейса. Удобно для больших разрешений экрана.\n\n#X Слишком высокое значение параметра приведет к тому, что элементы интерфейса не будут помещаться на экране.#!"
 SETTING_TOOLS_GUI_SCALING: "Масштабирование интерфейса инструментов"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Задаёт масштаб пользовательского интерфейса инструментов. Удобно для больших разрешений экрана.\n\n#X Слишком высокое значение параметра приведёт к тому, что элементы интерфейса не будут помещаться на экране!#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Перемещение мышью"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Свободное"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 направлений"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Выкл."
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nПоведение камеры при перемещении мышью."
 SETTING_SCROLL_SPEED: "Скорость перетаскивания"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nОпределяет скорость перемещения карты с помощью клавиатуры или мыши."
 SETTING_CAMERA_ROTATION_SPEED: "Скорость вращения камеры"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nСкорость вращения камеры."
 SETTING_ZOOM_SPEED: "Скорость приближения"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nСкорость приближения камеры."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Поведение приближения"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Относительно курсора"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Приближение к курсору"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Игнорировать курсор"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nПоведение камеры при приближении и отдалении относительно курсора."
 SETTING_INPUT_DEVICE: "Устройство ввода"
 SETTING_EDITOR: "Редактор"
 SETTING_EDITOR_POSTFIX: "Постфикс для команды редактора"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Команда открытия редактора"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Посмотреть журнал команд"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Команда открытия редактора кода"
 SETTING_GRACEFUL_EXIT: "Выход при ошибке"
 SETTING_LANGUAGE: "Язык"
 MOUSE_AND_KEYBOARD: "Клавиатура и мышь"
 GAMEPAD: "Геймпад"
 SETTING_MULTISAMPLING_DISABLED: "Отключено"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Отключено"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Отключено"
 #Editor
 SETTING_CAMERA_TILT: "Наклон камеры"
 SETTING_CAMERA_STRATEGY: "Тип камеры"
 SETTING_CENTERED_ZOOM_IN: "Приближение с центрированием"
 SETTING_CAMERA_SPEED: "Скорость камеры"
 CAMERA_TABLETOP: "Настольный вид"
 CAMERA_FPS: "От первого лица"
 CAMERA_WASD: "Стиль WASD"
 #Audio
 SETTING_Music: "Музыка"
 SETTING_Ambient: "Звуковое сопровождение"
 SETTING_Effects: "Эффекты"
 SETTING_Master: "Общий уровень"
 SETTING_VO: "Закадровый голос"
 SETTING_VO_TOOLTIP: "#T Громкость закадрового голоса\n#!Задаёт громкость закадрового голоса в игре."
 SETTING_Master_TOOLTIP: "#T Основная громкость\n#!Задает громкость всех звуков в игре."
 SETTING_Music_TOOLTIP: "#T Громкость музыки\n#!Задает громкость музыки."
 SETTING_Ambient_TOOLTIP: "#T Звуковое сопровождение\n#!Задает громкость звукового сопровождения."
 SETTING_SFX_TOOLTIP: "#T Звуковые эффекты\n#!Задает уровень громкости звуковых эффектов (боя и так далее)."
 SETTING_UI_TOOLTIP: "#T Интерфейс\n#!Задает уровень громкости звуков интерфейса."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Отладка журнала уровней"
 SETTING_AUDIO_DEVICE_PROFILE: "Аудиопрофиль"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Выберите аудиопрофиль под свои устройства."
 SETTING_AUDIO_OPTION_SPEAKERS: "Колонки"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Стандартное сочетание для колонок."
 SETTING_AUDIO_OPTION_HEADPHONES: "Наушники"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Сочетание, подходящее для наушников."
 SETTING_AUDIO_OPTION_TV: "ТВ"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Сочетание для колонок, встроенных в телевизор или монитор."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Ночной режим"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Приглушает звук для игры ночью, принижая высокие частоты и снижая дальность динамиков."
 SETTING_MUSIC_DENSITY: "Интенсивность музыки"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Определяет баланс между полноценными композициями, тишиной и музыкальным фоном. \n\nНасыщенная = В основном идёт последовательное воспроизведение музыкальных композиций, аналогично радиостанции. \nСбалансированная = Идеальный баланс между полноценными композициями, тишиной и созданием музыкальным фоном. \nЛёгкая = В основном фоновая музыка для передачи настроения игры без ощущения повтора после нескольких часов."
 #Game
 SETTING_AUTOSAVE: "Интервал автосохранений"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Задает частоту автосохранения игры."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Записывать автосохранения в облако (или нет)."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Всегда разворачивать игровую камеру на север или нет."
 NO_AUTOSAVE: "Без автосохранений"
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Скорость передачи файлов"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Задает максимальную скорость передачи файлов сохраненной игры в лобби сетевой игры.\n\nПонижение этого параметра может улучшить стабильность сети при подключении к сетевым играм, но это отрицательно скажется на времени загрузки файлов."
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Автосохранения в редакторе карт (мин.)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Частота автосохранений в редакторе карт (мин.)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Перемещение узлов"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Специальные возможности"
 SETTING_COLOR_BLIND_MODE: "Режим различимых цветов"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Заменяет цвета в игре на более различимые для людей, страдающих цветовой слепотой."
