l_french:
 SETTING_VALUE_WARNING:0 "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X Aller au-delà de $VALUE|%0$ va faire sortir les interfaces en dehors de l'écran.#!"
 RECOMMENDED_GUI_SCALE:1 "Aller au-delà de $VALUE|%0$ va faire sortir les interfaces en dehors de l'écran."
