l_korean:
 #General
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$초"
 SETTING_VALUE_MINUTES: "$VALUE$분"
 #Graphics
 SETTING_RENDERER: "렌더러"
 SETTING_RENDERER_TOOLTIP: "사용할 렌더러를 설정합니다."
 SETTING_VSYNC: "수직 동기화"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!게임과 모니터의 주사율을 동기화시켜 화면 티어링 현상을 감소시킵니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_PORTRAIT_MULTI_SAMPLING: "초상화 멀티 샘플링"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Alpha-To-Coverage 멀티 샘플링을 사용해 머리카락을 좀 더 부드럽게 만듭니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_MULTI_SAMPLING: "안티 앨리어싱 (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!멀티 샘플링 안티 앨리어싱 (MSAA)를 사용해 이미지의 가장자리를 부드럽게 만듭니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_ANTI_ALIASING: "안티 앨리어싱"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!안티 앨리어싱을 사용해 이미지의 가장자리를 부드럽게 만듭니다.\n\nFXAA 사용을 권장합니다."
 OPTION_ANTI_ALIASING_DISABLED: "비활성화"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "업스케일 방법"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\n업스케일 방법은 알고리즘 업샘플링을 통해 더 높은 디스플레이 해상도를 달성하는 데 사용될 수 있습니다. 이로 인해 성능이 향상될 수 있지만 시각적 아티팩트나 기타 예기치 않은 동작이 발생할 수 있습니다.\n\n사용 가능한 업스케일 방법은 그래픽 카드에 따라 다를 수 있습니다."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "업스케일 품질"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\n업스케일링 방법의 초점을 최고 품질에서부터 최고 성능까지 임의로 선택합니다."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "울트라 품질"
 OPTION_UPSCALE_QUALITY_QUALITY: "품질"
 OPTION_UPSCALE_QUALITY_BALANCED: "균형"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "성능"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "울트라 성능"
 SETTING_ANISOTROPIC_FILTERING: "텍스처 필터링"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!이방성 필터링을 사용해 텍스처 처리된 표면의 모습을 개선합니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_RESOLUTION: "해상도"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!게임의 이미지 품질을 설정합니다.\n\n해상도를 낮추면 성능이 향상됩니다.\n\n#X 지원되지 않는 비율의 게임 해상도를 사용할 경우 인터페이스가 화면 바깥에 표시될 수도 있습니다.#!"
 SETTING_WINDOWED_RESOLUTION: "창 화면 해상도"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!창 모드로 게임 실행 시 게임 창의 해상도를 설정합니다.\n\n#b 숫자#!x#b 숫자#! 형식이어야 합니다.\n\n#X 지원되지 않는 비율의 게임 해상도를 사용할 경우 인터페이스가 화면 바깥에 표시될 수도 있습니다.#!"
 SETTING_RENDER_SCALE: "렌더링 비율"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\n게임의 렌더링 해상도 비율은 사용자 인터페이스를 제외한 주 해상도와 관련되어 있습니다.\n\n설정값을 낮추면 성능이 향상되지만, 전반적인 선명도는 감소합니다. 100% 이상으로 높이면 선명도는 증가하지만 성능이 하락합니다."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "모니터"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!모니터가 여러 대일 경우 게임에 사용할 모니터를 선택합니다."
 SETTING_GRAPHICS_DEVICE: "그래픽 카드"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!게임에서 사용할 그래픽 카드를 선택합니다. \n\n내장 그래픽 카드나 소프트웨어 렌더러를 사용하면 성능이 저하될 수 있습니다."
 SETTING_SHADOW_MAP_RESOLUTION: "그림자 품질"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!그림자를 활성화할 경우 렌더링되는 그림자 해상도를 결정합니다.\n\n설정을 낮출수록 성능이 향상됩니다."
 SETTING_DISPLAY_MODE: "디스플레이 모드"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!게임의 화면 출력 방식을 결정합니다."
 SETTING_BLOOM_QUALITY: "블룸"
 SETTING_MESH_LOD_BIAS: "메쉬 Lod 품질"
 SETTING_MESH_LOD_FADE: "메쉬 Lod 페이드"
 SETTING_TERRAIN_SMOOTHING: "부드러운 지형"
 OPTION_FULLSCREEN: "전체 화면"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!전체 화면을 사용합니다. 해상도 설정에 따라 이미지의 선명도가 바뀝니다."
 OPTION_WINDOWED: "창모드"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!창모드를 사용합니다. 해상도 설정에 따라 창의 크기가 바뀝니다."
 OPTION_DISABLED: "비활성화"
 OPTION_OFF: "끄기"
 OPTION_LOW: "낮음"
 OPTION_MEDIUM: "보통"
 OPTION_HIGH: "높음"
 OPTION_ULTRA: "최상"
 OPTION_CUSTOM: "커스텀"
 OPTION_DEFAULT: "기본"
 SETTINGS_CATEGORY_UI: "인터페이스"
 SETTINGS_CATEGORY_GAME: "게임"
 SETTING_TEXTURE_QUALITY: "텍스처 품질"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\n불러온 텍스처의 해상도를 조절합니다.\n\n설정을 낮추면 성능이 향상됩니다."
 SETTING_QUALITY: "품질 사전 설정"
 SETTING_SFX: "특수 효과"
 SETTING_UI: "인터페이스"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!사전에 설정된 고급 그래픽 설정을 선택합니다.\n\n낮은 설정을 선택할수록 성능이 향상됩니다."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!굉장히 밝은 빛이 이미지의 다른 부분으로 퍼지는 \"블룸\" 효과를 활성화합니다.\n\n설정을 낮추면 성능이 향상됩니다."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!피사계 심도를 활성화하여, 카메라 렌즈를 구현하고 이미지에서 초점을 벗어난 지점을 흐릿하게 처리합니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!렌즈 플레어 효과를 활성화하여 블룸이 많은 영역에 나타나게 합니다. 이 효과를 보려면 블룸이 활성화되어 있어야 합니다. \n\n비활성화하면 성능이 향상됩니다."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!보조 렌즈 플레어 효과를 활성화하여 블룸이 많은 영역에 나타나게 합니다. 이 효과를 보려면 블룸이 활성화되어 있어야 합니다. \n\n비활성화하면 성능이 향상됩니다."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!지도의 스크린 스페이스 앰비언트 오클루전 적용 여부를 결정합니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_REFRACTION_TOOLTIP: "수면상의 굴절 효과 여부를 결정합니다."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\n활성화할 경우 수면 굴절의 품질을 조절합니다.\n\n설정을 낮추면 성능이 향상됩니다."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\n건물과 같은 지도 오브젝트의 가장 높은 품질 수준이 어느 정도일지 결정합니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\n유닛 모델과 같은 지도 오브젝트의 LOD (세밀도) 품질을 결정합니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!활성화할 경우, 화면을 확대하거나 축소했을 때 세밀도 (LOD) 단계마다 부드러운 3D 모델 전환이 이루어집니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_PROVINCE_NAMES_TOOLTIP: "지도상에 존재하는 도시 및 지역의 이름을 어떻게 표시할지 결정합니다."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "국경에 통행 불가능한 지형도 포함할지 결정합니다."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\n유저 인터페이스의 언어를 설정합니다."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Paradox 계정 이메일"
 SETTING_FRAMERATE_CAP: "최대 프레임 수(FPS)"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\n게임을 렌더링할 최대 프레임 수(FPS)를 결정합니다.\n\n설정값을 낮추면 전력 소모가 감소합니다."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "텍스처 스트리밍"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\n필요할 때 텍스처를 불러옵니다.\n\nCPU 타임이 늘어나는 대신 GPU 메모리 사용량이 감소합니다. 메모리가 적은 GPU의 퍼포먼스가 개선됩니다."
 SETTING_TEXTURE_STREAMING_CACHE: "텍스처 스트리밍 캐시 용량"
 SETTING_VALUE_MB: "$VALUE$MB"
 #GUI
 SETTING_ANIMATION_SPEED: "애니메이션 속도"
 SETTING_GUI_SCALING: "GUI 비율"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!전체 유저 인터페이스의 비율을 설정합니다. 높은 해상도를 사용할 때 유용한 기능입니다.\n\n#X 너무 높게 설정하면 인터페이스와 화면이 부조화를 이룰 수 있습니다!#!"
 SETTING_TOOLS_GUI_SCALING: "툴 GUI 스케일링"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!툴 사용자 인터페이스의 배율을 설정합니다. 화면 해상도가 높을 때 유용합니다.\n\n#X 너무 높게 설정하면 인터페이스가 화면에 어긋나게 나타날 수 있습니다!#!"
 #System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "마우스 이동"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "자유"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8방향"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "비활성화"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\n마우스 이동 시의 카메라 움직임 방식을 결정합니다."
 SETTING_SCROLL_SPEED: "이동 속도"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\n키보드 또는 마우스 사용 시의 지도 이동 속도를 결정합니다."
 SETTING_CAMERA_ROTATION_SPEED: "카메라 회전 속도"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\n카메라 회전 속도를 결정합니다."
 SETTING_ZOOM_SPEED: "확대/축소 속도"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\n카메라 확대/축소 속도를 결정합니다."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "확대/축소 방식"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "커서 연동식"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "커서 확대/축소"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "커서 무시"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\n확대/축소 시 카메라가 마우스 커서를 따라 어떻게 움직이는지를 결정합니다."
 SETTING_INPUT_DEVICE: "입력 장치"
 SETTING_EDITOR: "에디터"
 SETTING_EDITOR_POSTFIX: "에디터 포스트픽스"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "에디터 명령창 실행"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "로그 명령창 표시"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "코드 에디터 명령창 실행"
 SETTING_GRACEFUL_EXIT: "단계적 종료"
 SETTING_LANGUAGE: "언어"
 MOUSE_AND_KEYBOARD: "마우스 & 키보드"
 GAMEPAD: "게임패드"
 SETTING_MULTISAMPLING_DISABLED: "비활성화"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "비활성화"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "비활성화"
 #Editor
 SETTING_CAMERA_TILT: "카메라 기울기"
 SETTING_CAMERA_STRATEGY: "카메라 유형"
 SETTING_CENTERED_ZOOM_IN: "중앙 확대"
 SETTING_CAMERA_SPEED: "카메라 속도"
 CAMERA_TABLETOP: "테이블탑"
 CAMERA_FPS: "1인칭"
 CAMERA_WASD: "WASD 방식"
 #Audio
 SETTING_Music: "음악"
 SETTING_Ambient: "환경 효과음"
 SETTING_Effects: "효과음"
 SETTING_Master: "전체"
 SETTING_VO: "음성"
 SETTING_VO_TOOLTIP: "#T 음성 음량\n#!게임 내 음성 오디오의 음량을 조절합니다."
 SETTING_Master_TOOLTIP: "#T 전체 음량\n#!게임에 사용되는 모든 소리의 음량을 조절합니다."
 SETTING_Music_TOOLTIP: "#T 음악 음량\n#!음악의 음량을 조절합니다."
 SETTING_Ambient_TOOLTIP: "#T 환경음 음량\n#!환경음의 음량을 조절합니다."
 SETTING_SFX_TOOLTIP: "#T 효과음 음량\n#!전투와 같은 효과음의 음량을 조절합니다."
 SETTING_UI_TOOLTIP: "#T 인터페이스 음량\n#!유저 인터페이스의 음량을 조절합니다."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "디버그 로그 수준"
 SETTING_AUDIO_DEVICE_PROFILE: "오디오 프로필"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!환경에 맞는 오디오 프로필을 선택하십시오."
 SETTING_AUDIO_OPTION_SPEAKERS: "스피커"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!$SETTING_AUDIO_OPTION_SPEAKERS$ 기본 믹스 설정입니다."
 SETTING_AUDIO_OPTION_HEADPHONES: "헤드폰"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!$SETTING_AUDIO_OPTION_HEADPHONES$에 맞춰 조정된 믹스 설정입니다."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!$SETTING_AUDIO_OPTION_TV$ 및 모니터 스피커에 맞춰진 믹스 설정입니다."
 SETTING_AUDIO_OPTION_NIGHTMODE: "심야 모드"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!심야 플레이에 적합하도록 음향을 부드럽게 완화합니다. 고음을 줄이고 다이내믹 레인지를 압축합니다."
 SETTING_MUSIC_DENSITY: "음악 밀도"
 SETTING_MUSIC_DENSITY_TOOLTIP: "전체 노래, 침묵, 분위기 음악 구간의 균형을 조정합니다. \n\n격렬함 = 주로 노래 전체를 연속으로 재생합니다. '라디오 방송'을 생각하면 됩니다. \n균형 = 노래, 침묵, 분위기의 완벽한 조화를 경험할 수 있는 설정입니다. \n편안함 = 편안한 음악을 중심으로 재생하여 좋은 분위기를 조성합니다. 장시간 플레이 시 반복적인 느낌이 다소 줄어듭니다."
 #Game
 SETTING_AUTOSAVE: "자동 저장 간격"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!자동 저장의 빈도를 설정합니다."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "자동 저장 파일의 클라우드 저장 여부를 결정합니다."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "카메라를 항상 북쪽으로 고정할지 여부를 결정합니다."
 NO_AUTOSAVE: "자동 저장 없음"
 #Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "파일 전송 속도"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!멀티플레이 대기실에서 저장 게임 파일을 전송할 최대 속도를 결정합니다.\n\n설정값을 낮추면 멀티플레이 게임 참여 시의 네트워크 안정성이 향상되지만, 멀티플레이 불러오기 시간에 부정적인 영향이 있을 수 있습니다."
 #Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "지도 에디터 자동 저장 (분)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "지도 에디터 자동 저장 간격 (분)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "노드 에디터 드래그 이동 모드"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
 #Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "접근성"
 SETTING_COLOR_BLIND_MODE: "색맹 모드"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!색맹 유형에 따라 좀 더 손쉽게 분간할 수 있도록 게임 전반에 사용되는 텍스트 색상을 변경합니다."
