l_german:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Eine Skalierung über einen Wert von $VALUE|%0$ führt dazu, dass Benutzeroberflächen außerhalb des Bildschirms liegen#!"
 RECOMMENDED_GUI_SCALE: "Eine Skalierung über einen Wert von $VALUE|%0$ führt dazu, dass Benutzeroberflächen außerhalb des Bildschirms liegen"
