l_turkish:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ saniye"
 SETTING_VALUE_MINUTES:0 "$VALUE$ dakika"
 # Graphics
 SETTING_RENDERER:0 "İşleyici"
 SETTING_VSYNC:0 "Dikey Eşitleme"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Oyunla monitörünün aynı kare hızına sahip olmasını sağlayarak ekran yırtılmalarını azaltır.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Portre Çoklu Örnekleme"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Alpha-To-Coverage yöntemi için çoklu örnekleme kullanarak saçları daha yumuşak hale getirir.\n\nBu ayarın düşürülmesi performansı arttırır."
 SETTING_MULTI_SAMPLING:0 "Kenar Yumuşatma (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!MSAA (çoklu örneklemeli kenar yumuşatma) tekniğini kullanarak görüntülerin kenarlarını daha pürüzsüz hale getirir.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_ANTI_ALIASING:0 "Kenar Yumuşatma"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Görüntülerin kenarlarını daha pürüzsüz hale getirir.\n\nFXAA önerilir."
 OPTION_ANTI_ALIASING_DISABLED:0 "Kapalı"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Doku Filtreleme"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Eşyönsüz filtreleme dokulu yüzeylerin daha iyi görünmesini sağlar.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_FULLSCREEN_RESOLUTION:0 "Çözünürlük"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Oyunun görüntü kalitesini belirler.\n\nÇözünürlüğün düşürülmesi performansı arttırabilir.\n\n#X Desteklenmeyen görüntü oranlarını gerektiren çözünürlükler, arayüzlerin ekranın dışına taşmasına sebep olabilir.#!"
 SETTING_WINDOWED_RESOLUTION:0 "Pencere Çözünürlüğü"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Oyunun pencereli modda çalışması halinde oyun penceresinin çözünürlüğünü belirler.\n\n#b SAYI#!x#b SAYI#! formatında olmalıdır.\n\n#X Desteklenmeyen görüntü oranlarını gerektiren çözünürlükler, arayüzlerin ekranın dışına taşmasına sebep olabilir.#!"
 SETTING_RENDER_SCALE:0 "İşleme Ölçeği"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nOyunun işlendiği çözünürlüğün ana çözünürlüğe oranı. Kullanıcı arayüzünün çözünürlüğü buna dahil değildir.\n\nBu ayarın düşürülmesi performansı arttırabilir fakat genel görüntü kalitesini düşürür. Öte yandan bu ayarın %100'ün üzerine çıkarılması görüntü kalitesini arttırabilir fakat performansı düşürebilir."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Monitör"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Birden çok monitörün varsa oyunun kullanacağı monitörü buradan seçebilirsin."
 SETTING_GRAPHICS_DEVICE:0 "Ekran Kartı"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Oyunun kullanacağı ekran kartı.\n\nTümleşik bir ekran kartı ya da yazılım işleyici kullanmak oyun performansını düşürebilir."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Gölge Kalitesi"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Gölgelerin devrede olması halinde gölge haritalamasının çizim çözünürlüğünü belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_DISPLAY_MODE:0 "Görüntü Modu"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Oyunun ekranda nasıl görüntüleneceğini belirler."
 SETTING_BLOOM:0 "Işık Parlamaları"
 SETTING_MESH_LOD_BIAS:0 "Model Ayrıntı Düzeyi Kalitesi"
 SETTING_MESH_LOD_FADE:0 "Model Ayrıntı Düzeyi Azalması"
 SETTING_TERRAIN_SMOOTHING:1 "Arazi Pürüzsüzleştirme"
 OPTION_FULLSCREEN:0 "Tam Ekran"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Oyunu ekranın tamamını kullanarak görüntüle. Çözünürlük ayarı, görüntünün netliğini değiştirir."
 OPTION_WINDOWED:0 "Pencere"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Oyunu bir pencerede görüntüle. Çözünürlük ayarı, pencerenin boyutunu değiştirir."
 OPTION_DISABLED:1 "Kapalı"
 OPTION_OFF:0 "Kapalı"
 OPTION_LOW:0 "Düşük"
 OPTION_MEDIUM:0 "Orta"
 OPTION_HIGH:0 "Yüksek"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Özel"
 OPTION_DEFAULT:1 "Varsayılan"
 SETTINGS_CATEGORY_UI:0 "Arayüz"
 SETTINGS_CATEGORY_GAME:0 "Oyun"
 SETTING_TEXTURE_QUALITY:1 "Doku Kalitesi"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nYüklenen dokuların çözünürlüğünü belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_QUALITY:0 "Kalite Ön Ayarı"
 SETTING_SFX:0 "Özel Efektler"
 SETTING_UI:0 "Arayüz"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Gelişmiş grafik seçenekleri için aşağıdan bir ön ayar seç.\n\nDüşük bir ön ayar performansı arttırır."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Aşırı parlak ışıkların görüntüde çeşitli yerlere dağıldığı bir "parlama" efekti açar.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Bir kamera lensini simüle etmek için alan derinliğini açar ve görüntüde odağın dışında kalan yerleri bulanıklaştırır.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!SSAO (ekran alanı çevresel perdeleme) yönteminin haritaya uygulanıp uygulanmayacağını belirler.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_REFRACTION_TOOLTIP:0 "Suda ışık kırılmalarının oluşup oluşmayacağını belirler."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nAçık olması halinde suda oluşacak ışık kırılmalarının kalitesini belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nHaritadaki nesnelerin (binalar vb.) kalite düzeyini belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nHaritadaki nesnelerin (birim modelleri vb.) ayrıntı düzeyi kalitesini belirler.\n\nBu ayarın düşürülmesi performansı arttırabilir."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Bu ayar açıldığında, haritaya yakınlaştırma-uzaklaştırma yaparken 3D modellerin ayrıntı düzeyleri arasında pürüzsüz bir şekilde geçiş yapılır.\n\nBu ayarı kapatmak performansı arttırabilir."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Şehir ve idari bölge adlarının haritada nasıl görüneceğini belirler."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Geçilmez arazilerin haritada ülkelerin sınırlarına dahil edilip edilmeyeceğini belirler."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nKullanıcı arayüzünün dilini belirler."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Paradox hesabın için kullandığın e-posta adresi"
 SETTING_FRAMERATE_CAP:1 "Maksimum FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nOyunun çalışacağı maksimum FPS (saniyelik kare hızı).\n\nBu ayarın düşürülmesi güç tüketimini azaltabilir."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "Doku Akışı"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nDokular ihtiyaç oldukça yüklenir.\n\nİşlemciye bir miktar yük ekleyerek ekran kartının bellek kullanımını azaltır. Bellek boyutu düşük olan ekran kartlarında performansı arttırabilir."
 SETTING_TEXTURE_STREAMING_CACHE:0 "Doku Akışı Önbellek Boyutu"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Animasyon hızı"
 SETTING_GUI_SCALING:0 "Grafiksel Kullanıcı Arayüzü (GUI) Ölçekleme"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Bütün kullanıcı arayüzlerinin ölçeğini belirler. Yüksek ekran çözünürlükleri için kullanışlı bir ayardır.\n\n#X Bu ayar fazla yükseltilirse arayüzler ekrana düzgün bir şekilde sığmaz!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Fare Kaydırması"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Serbest"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 yönlü"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Kapalı"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nFareyle ekranı kaydırırken kameranın nasıl davranacağını belirler."
 SETTING_SCROLL_SPEED:1 "Kaydırma Hızı"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nKlavye ya da fareyi kullanırken haritanın ne kadar hızlı kaydırılacağını belirler."
 SETTING_CAMERA_ROTATION_SPEED:1 "Kamera Dönüş Hızı"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nKameranın dönüş hızı."
 SETTING_ZOOM_SPEED:1 "Yakınlaştırma-Uzaklaştırma Hızı"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nKameranın yakınlaştırma-uzaklaştırma hızı."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Yakınlaştırma-Uzaklaştırma Davranışı"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Göreli imleç"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "İmlece yakınlaş"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "İmleci görmezden gel"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nYakınlaştırma-uzaklaştırma yaparken kameranın fare imlecine göre nasıl davranacağını belirler."
 SETTING_INPUT_DEVICE:0 "Giriş aygıtı"
 SETTING_EDITOR:0 "Editör"
 SETTING_EDITOR_POSTFIX:0 "Editör soneki"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Editör açma komutu"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Günlük komutunu göster"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Kod editörü açma komutu"
 SETTING_GRACEFUL_EXIT:0 "Kontrollü çıkış"
 SETTING_LANGUAGE:0 "Dil"
 MOUSE_AND_KEYBOARD:0 "Fare ve klavye"
 GAMEPAD:0 "Oyun kumandası"
 SETTING_MULTISAMPLING_DISABLED:0 "Kapalı"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Kapalı"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Kapalı"
 # Editor
 SETTING_CAMERA_TILT:0 "Kamera eğimi"
 SETTING_CAMERA_STRATEGY:0 "Kamera türü"
 SETTING_CENTERED_ZOOM_IN:0 "Ortalanmış yakınlaştırma"
 SETTING_CAMERA_SPEED:0 "Kamera hızı"
 CAMERA_TABLETOP:0 "Masa oyunu"
 CAMERA_FPS:0 "Birinci şahıs"
 CAMERA_WASD:0 "WASD tarzı"
 # Audio
 SETTING_Music:0 "Müzik"
 SETTING_Ambient:0 "Ortam"
 SETTING_Effects:0 "Efektler"
 SETTING_Master:0 "Ana Ses"
 SETTING_Master_TOOLTIP:0 "#T Ana Ses Düzeyi\n#!Oyundaki tüm seslerin düzeyini belirler."
 SETTING_Music_TOOLTIP:0 "#T Müzik Düzeyi\n#!Çalan müziklerin ses düzeyini belirler."
 SETTING_Ambient_TOOLTIP:0 "#T Ortam Sesleri Düzeyi\n#!Çevresel ambiyans seslerinin düzeyini belirler."
 SETTING_SFX_TOOLTIP:0 "#T Ses Efekt Düzeyi\n#!Savaş vb. ses efektlerinin düzeyini belirler."
 SETTING_UI_TOOLTIP:0 "#T Arayüz Ses Düzeyi\n#!Kullanıcı arayüzünün ses düzeyini belirler."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Hata Ayıklama Günlüğü Düzeyi"
 SETTING_AUDIO_DEVICE_PROFILE:0 "Ses Profili"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Kurulumuna uygun bir ses profili seç."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Hoparlör"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!$SETTING_AUDIO_OPTION_SPEAKERS$ için varsayılan ses karıştırıcısı."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Kulaklık"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!$SETTING_AUDIO_OPTION_HEADPHONES$ için ayarlanan ses karıştırıcısı."
 SETTING_AUDIO_OPTION_TV:0 "Televizyon"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!$SETTING_AUDIO_OPTION_TV$ ve monitör hoparlörü için ayarlanan ses karıştırıcısı."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Gece Modu"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Gece oynanan oyunlar için tiz sesleri kısarak ve dinamik aralığı sıkıştırarak sesi yumuşatır."
 SETTING_MUSIC_DENSITY:0 "Densidad de la música"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "Tam şarkılar, sessizlik ve duruma uygun müzik segmentleri arasındaki dengeyi kontrol eder.\n\nYoğun = Çoğunlukla bir radyo istasyonu gibi arka arkaya şarkılar çalınır.\nDengeli = Şarkılar, sessizlik ve duruma uygun müzikler arasında kusursuz bir denge kurulur.\nSakin = Çoğunlukla daha huzurlu bir ortam sunan ve tekrarlanma sıklığı daha düşük olan rahatlatıcı müzik segmentleri çalınır."
  # Game
 SETTING_AUTOSAVE:0 "Otomatik Kayıt Aralığı"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Oyunun hangi sıklıkta otomatik kayıt yapacağını belirler."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Otomatik kayıtların buluta kaydedilip kaydedilmeyeceğini belirler."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Kameranın kuzey yönüne kilitlenip kilitlenmeyeceğini belirler."
 NO_AUTOSAVE:0 "Otomatik Kaydı Kapat"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "Dosya Aktarım Hızı"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $Dosya Aktarım Hızı$\n#!Çok oyunculu lobide kayıt dosyalarının maksimum aktarım hızını belirler.\n\nBu ayarın düşürülmesi çok oyunculu oyunlara bağlanırken ağ istikrarını geliştirebilir ancak çok oyunculu yükleme sürelerine olumsuz etki eder."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Harita Editöründe Otomatik Kayıt (dakika)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Harita Editörü Otomatik Kayıt Aralığı (dakika)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Nokta Editörü Sürükleme-Kaydırma Modu"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Erişilebilirlik"
 SETTING_COLOR_BLIND_MODE:0 "Renk Körü Modu"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Oyun metinlerinin rengini farklı renk körlüklerine göre değiştirerek metinlerin ayırt edilmesini kolaylaştırır."
