l_braz_por:
 SETTING_VALUE_WARNING:0 "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X Ultrapassar $VALUE|%0$ fará as interfaces aparecerem fora da tela#!"
 RECOMMENDED_GUI_SCALE:1 "Ultrapassar $VALUE|%0$ fará as interfaces aparecerem fora da tela"
