l_korean:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$초"
 SETTING_VALUE_MINUTES:0 "$VALUE$분"
 # Graphics
 SETTING_RENDERER:0 "렌더러"
 SETTING_RENDERER_TOOLTIP:0 "사용할 렌더러를 설정합니다."
 SETTING_VSYNC:0 "수직 동기화"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!게임과 모니터의 주사율을 동기화시켜 화면 티어링 현상을 감소시킵니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "초상화 멀티 샘플링"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Alpha-To-Coverage 멀티 샘플링을 사용해 머리카락을 좀 더 부드럽게 만듭니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_MULTI_SAMPLING:0 "안티 앨리어싱 (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!멀티 샘플링 안티 앨리어싱 (MSAA)를 사용해 이미지의 가장자리를 부드럽게 만듭니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_ANTI_ALIASING:0 "안티 앨리어싱"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!안티 앨리어싱을 사용해 이미지의 가장자리를 부드럽게 만듭니다.\n\nFXAA 사용을 권장합니다."
 OPTION_ANTI_ALIASING_DISABLED:0 "비활성화"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "텍스처 필터링"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!이방성 필터링을 사용해 텍스처 처리된 표면의 모습을 개선합니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_FULLSCREEN_RESOLUTION:0 "해상도"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!게임의 이미지 품질을 설정합니다.\n\n해상도를 낮추면 성능이 향상됩니다.\n\n#X 지원되지 않는 비율의 게임 해상도를 사용할 경우 인터페이스가 화면 바깥에 표시될 수도 있습니다.#!"
 SETTING_WINDOWED_RESOLUTION:0 "창 화면 해상도"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!창 모드로 게임 실행 시 게임 창의 해상도를 설정합니다.\n\n#b 숫자#!x#b 숫자#! 형식이어야 합니다.\n\n#X 지원되지 않는 비율의 게임 해상도를 사용할 경우 인터페이스가 화면 바깥에 표시될 수도 있습니다.#!"
 SETTING_RENDER_SCALE:0 "렌더링 비율"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\n게임의 렌더링 해상도 비율은 사용자 인터페이스를 제외한 주 해상도와 관련되어 있습니다.\n\n설정값을 낮추면 성능이 향상되지만, 전반적인 선명도는 감소합니다. 100% 이상으로 높이면 선명도는 증가하지만 성능이 하락합니다."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "모니터"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!모니터가 여러 대일 경우 게임에 사용할 모니터를 선택합니다."
 SETTING_GRAPHICS_DEVICE:0 "그래픽 카드"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!게임에서 사용할 그래픽 카드를 선택합니다. \n\n내장 그래픽 카드나 소프트웨어 렌더러를 사용하면 성능이 저하될 수 있습니다."
 SETTING_SHADOW_MAP_RESOLUTION:0 "그림자 품질"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!그림자를 활성화할 경우 렌더링되는 그림자 해상도를 결정합니다.\n\n설정을 낮출수록 성능이 향상됩니다."
 SETTING_DISPLAY_MODE:0 "디스플레이 모드"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!게임의 화면 출력 방식을 결정합니다."
 SETTING_BLOOM:0 "블룸"
 SETTING_MESH_LOD_BIAS:0 "메쉬 Lod 품질"
 SETTING_MESH_LOD_FADE:0 "메쉬 Lod 페이드"
 SETTING_TERRAIN_SMOOTHING:1 "부드러운 지형"
 OPTION_FULLSCREEN:0 "전체 화면"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!전체 화면을 사용합니다. 해상도 설정에 따라 이미지의 선명도가 바뀝니다."
 OPTION_WINDOWED:0 "창모드"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!창모드를 사용합니다. 해상도 설정에 따라 창의 크기가 바뀝니다."
 OPTION_DISABLED:1 "비활성화"
 OPTION_OFF:0 "끄기"
 OPTION_LOW:0 "낮음"
 OPTION_MEDIUM:0 "보통"
 OPTION_HIGH:0 "높음"
 OPTION_ULTRA:1 "최상"
 OPTION_CUSTOM:0 "커스텀"
 OPTION_DEFAULT:1 "기본"
 SETTINGS_CATEGORY_UI:0 "인터페이스"
 SETTINGS_CATEGORY_GAME:0 "게임"
 SETTING_TEXTURE_QUALITY:1 "텍스처 품질"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\n불러온 텍스처의 해상도를 조절합니다.\n\n설정을 낮추면 성능이 향상됩니다."
 SETTING_QUALITY:0 "품질 사전 설정"
 SETTING_SFX:0 "특수 효과"
 SETTING_UI:0 "인터페이스"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!사전에 설정된 고급 그래픽 설정을 선택합니다.\n\n낮은 설정을 선택할수록 성능이 향상됩니다."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!"블룸" 이펙트를 활성화하여, 아주 밝은 빛이 이미지의 다른 부분으로 흘러 넘치도록 합니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!피사계 심도를 활성화하여, 카메라 렌즈를 구현하고 이미지에서 초점을 벗어난 지점을 흐릿하게 처리합니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!지도의 스크린 스페이스 앰비언트 오클루전 적용 여부를 결정합니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_REFRACTION_TOOLTIP:0 "수면상의 굴절 효과 여부를 결정합니다."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\n활성화할 경우 수면 굴절의 품질을 조절합니다.\n\n설정을 낮추면 성능이 향상됩니다."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\n건물과 같은 지도 오브젝트의 가장 높은 품질 수준이 어느 정도일지 결정합니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\n유닛 모델과 같은 지도 오브젝트의 LOD (세밀도) 품질을 결정합니다.\n\n설정값을 낮추면 성능이 향상됩니다."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!활성화할 경우, 화면을 확대하거나 축소했을 때 세밀도 (LOD) 단계마다 부드러운 3D 모델 전환이 이루어집니다.\n\n비활성화하면 성능이 향상됩니다."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "지도상에 존재하는 도시 및 지역의 이름을 어떻게 표시할지 결정합니다."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "국경에 통행 불가능한 지형도 포함할지 결정합니다."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\n유저 인터페이스의 언어를 설정합니다."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Paradox 계정 이메일"
 SETTING_FRAMERATE_CAP:1 "최대 프레임 수(FPS)"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\n게임을 렌더링할 최대 프레임 수(FPS)를 결정합니다.\n\n설정값을 낮추면 전력 소모가 감소합니다."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "텍스처 스트리밍"
 SETTING_TEXTURE_STREAMING_CACHE:0 "텍스처 스트리밍 캐시 용량"
 SETTING_VALUE_MB:0 "$VALUE$MB"
 # GUI
 SETTING_ANIMATION_SPEED:0 "애니메이션 속도"
 SETTING_GUI_SCALING:0 "GUI 비율"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!전체 유저 인터페이스의 비율을 설정합니다. 높은 해상도를 사용할 때 유용한 기능입니다.\n\n#X 너무 높게 설정하면 인터페이스와 화면이 부조화를 이룰 수 있습니다!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "마우스 이동"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "자유"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8방향"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "비활성화"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\n마우스 이동 시의 카메라 움직임 방식을 결정합니다."
 SETTING_SCROLL_SPEED:1 "이동 속도"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\n키보드 또는 마우스 사용 시의 지도 이동 속도를 결정합니다."
 SETTING_CAMERA_ROTATION_SPEED:1 "카메라 회전 속도"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\n카메라 회전 속도를 결정합니다."
 SETTING_ZOOM_SPEED:1 "확대/축소 속도"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\n카메라 확대/축소 속도를 결정합니다."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "확대/축소 방식"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "커서 연동식"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "커서 확대/축소"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "커서 무시"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\n확대/축소 시 카메라가 마우스 커서를 따라 어떻게 움직이는지를 결정합니다."
 SETTING_INPUT_DEVICE:0 "입력 장치"
 SETTING_EDITOR:0 "에디터"
 SETTING_EDITOR_POSTFIX:0 "에디터 포스트픽스"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "에디터 명령창 실행"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "로그 명령창 표시"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "코드 에디터 명령창 실행"
 SETTING_GRACEFUL_EXIT:0 "단계적 종료"
 SETTING_LANGUAGE:0 "언어"
 MOUSE_AND_KEYBOARD:0 "마우스 & 키보드"
 GAMEPAD:0 "게임패드"
 SETTING_MULTISAMPLING_DISABLED:0 "비활성화"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "비활성화"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "비활성화"
 # Editor
 SETTING_CAMERA_TILT:0 "카메라 기울기"
 SETTING_CAMERA_STRATEGY:0 "카메라 유형"
 SETTING_CENTERED_ZOOM_IN:0 "중앙 확대"
 SETTING_CAMERA_SPEED:0 "카메라 속도"
 CAMERA_TABLETOP:0 "테이블탑"
 CAMERA_FPS:0 "1인칭"
 CAMERA_WASD:0 "WASD 방식"
 # Audio
 SETTING_Music:0 "음악"
 SETTING_Ambient:0 "환경 효과음"
 SETTING_Effects:0 "효과음"
 SETTING_Master:0 "전체"
 SETTING_Master_TOOLTIP:0 "#T 전체 음량\n#!게임에 사용되는 모든 소리의 음량을 조절합니다."
 SETTING_Music_TOOLTIP:0 "#T 음악 음량\n#!음악의 음량을 조절합니다."
 SETTING_Ambient_TOOLTIP:0 "#T 환경음 음량\n#!환경음의 음량을 조절합니다."
 SETTING_SFX_TOOLTIP:0 "#T 효과음 음량\n#!전투와 같은 효과음의 음량을 조절합니다."
 SETTING_UI_TOOLTIP:0 "#T 인터페이스 음량\n#!유저 인터페이스의 음량을 조절합니다."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "디버그 로그 수준"
 SETTING_AUDIO_DEVICE_PROFILE:0 "오디오 프로필"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!환경에 맞는 오디오 프로필을 선택하십시오."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "스피커"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!$SETTING_AUDIO_OPTION_SPEAKERS$ 기본 믹스 설정입니다."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "헤드폰"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!$SETTING_AUDIO_OPTION_HEADPHONES$에 맞춰 조정된 믹스 설정입니다."
 SETTING_AUDIO_OPTION_TV:0 "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!$SETTING_AUDIO_OPTION_TV$ 및 모니터 스피커에 맞춰진 믹스 설정입니다."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "심야 모드"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!심야 플레이에 적합하도록 음향을 부드럽게 완화합니다. 고음을 줄이고 다이내믹 레인지를 압축합니다."
 SETTING_MUSIC_DENSITY:0 "음악 밀도"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "전체 노래, 침묵, 분위기 음악 구간의 균형을 조정합니다. \n\n격렬함 = 주로 노래 전체를 연속으로 재생합니다. '라디오 방송'을 생각하면 됩니다. \n균형 = 노래, 침묵, 분위기의 완벽한 조화를 경험할 수 있는 설정입니다. \n편안함 = 편안한 음악을 중심으로 재생하여 좋은 분위기를 조성합니다. 장시간 플레이 시 반복적인 느낌이 다소 줄어듭니다."
  # Game
 SETTING_AUTOSAVE:0 "자동 저장 간격"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!자동 저장의 빈도를 설정합니다."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "자동 저장 파일의 클라우드 저장 여부를 결정합니다."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "카메라를 항상 북쪽으로 고정할지 여부를 결정합니다."
 NO_AUTOSAVE:0 "자동 저장 없음"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "파일 전송 속도"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $File Transfer Speed$\n#!멀티플레이 대기실에서 저장 게임 파일을 전송할 최대 속도를 결정합니다.\n\n설정값을 낮추면 멀티플레이 게임 참여 시의 네트워크 안정성이 향상되지만, 멀티플레이 불러오기 시간에 부정적인 영향이 있을 수 있습니다."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "지도 에디터 자동 저장 (분)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "지도 에디터 자동 저장 간격 (분)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "노드 에디터 드래그 이동 모드"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "접근성"
 SETTING_COLOR_BLIND_MODE:0 "색맹 모드"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!색맹 유형에 따라 좀 더 손쉽게 분간할 수 있도록 게임 전반에 사용되는 텍스트 색상을 변경합니다."

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 SETTING_MOUSE_PANNING:0 "화면 가장자리 이동"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!마우스 커서를 화면 혹은 창의 가장자리로 움직일 때의 지도 이동 여부를 설정합니다."
