l_spanish:
 SETTING_VALUE_WARNING:0 "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X Si el valor es superior al $VALUE|%0$, las interfaces aparecerán fuera de la pantalla#!"
 RECOMMENDED_GUI_SCALE:1 "Si el valor es superior al $VALUE|%0$, las interfaces aparecerán fuera de la pantalla"
