l_german:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ Sekunden"
 SETTING_VALUE_MINUTES:0 "$VALUE$ Minuten"
 # Graphics
 SETTING_RENDERER:0 "Renderer"
 SETTING_RENDERER_TOOLTIP:0 "Legt die Art des Renderers fest, der verwendet werden soll."
 SETTING_VSYNC:0 "VSync"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Synchronisiert die Bildfrequenz des Spiels mit der des Bildschirms, um ein Verschwimmen des Bildes zu reduzieren.\n\nEine Deaktivierung kann die Leistung verbessern."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Porträt-Multisampling"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Der Einsatz von Multi-Sampling für Alpha-To-Coverage deckt das Haar glatter ab.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MULTI_SAMPLING:0 "Multisampling"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Die Verwendung von Multi-Sample-Anti-Aliasing (MSAA) macht die Kanten der Bilder glatter.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_ANTI_ALIASING:0 "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Die Verwendung von Anti-Aliasing macht die Kanten der Bilder glatter.\n\nFXAA wird empfohlen."
 OPTION_ANTI_ALIASING_DISABLED:0 "Deaktiviert"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Anisotrope Filterung"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Die Nutzung von anisotropem Filtern führt dazu, dass Oberflächen besser aussehen.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_FULLSCREEN_RESOLUTION:0 "Auflösung"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Legt die Auflösungsqualität des Spiels fest.\n\nEine niedrigere Auflösung kann die Leistung erhöhen.\n\n#X Die Spielauflösung bei nicht unterstützten Seitenverhältnissen kann dafür sorgen, dass die Oberfläche außerhalb des Bildschirms angezeigt wird#!"
 SETTING_WINDOWED_RESOLUTION:0 "Fensterauflösung"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Legt die Auflösung des Spiels fest, wenn das Spiel im Fenster läuft.\n\nMuss im Format #b ZAHL#!x#b ZAHL#! vorliegen.\n\n#X Die Spielauflösung bei nicht unterstützten Seitenverhältnissen kann dafür sorgen, dass die Oberfläche außerhalb des Bildschirms angezeigt wird#!"
 SETTING_RENDER_SCALE:0 "Render-Skalierung"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nDas Skalieren der Render-Auflösung des Spiels im Verhältnis zur Hauptauflösung mit Ausnahme der Benutzeroberfläche.\n\nNiedrigere Einstellungen können die Leistung verbessern, aber die allgemeine Bildqualität verschlechtern. Werden 100 % Bildqualität überschritten, wird dies sehr wahrscheinlich die Leistung verschlechtern."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Anzeige"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Falls mehrere Monitore angeschlossen sind, wählt man hier aus, welchen das Spiel nutzen soll."
 SETTING_GRAPHICS_DEVICE:0 "Grafikkarte"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Wählt aus, welche Grafikkarte das Spiel nutzen soll.\n\nEine integrierte Grafikkarte oder einen Software-Renderer zu benutzen, kann die Leistung reduzieren."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Schattenqualität"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Bestimmt die Auflösung, mit der Schatten gerendert werden, falls diese aktiviert sind.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_DISPLAY_MODE:0 "Anzeigemodus"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Bestimmt, wie das Spiel auf dem Bildschirm angezeigt wird"
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Objektqualität"
 SETTING_MESH_LOD_FADE:0 "Objektübergänge"
 SETTING_TERRAIN_SMOOTHING:1 "Geländeglättung"
 OPTION_FULLSCREEN:0 "Vollbild"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Das Spiel nutzt den gesamten Bildschirm. Die Auflösungseinstellung legt fest, wie scharf das Bild dargestellt wird."
 OPTION_WINDOWED:0 "Fenster"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Öffnet das Spiel im Fenstermodus. Die Auflösungseinstellung legt die Größe des Fensters fest."
 OPTION_DISABLED:1 "Deaktiviert"
 OPTION_OFF:0 "Aus"
 OPTION_LOW:0 "Niedrig"
 OPTION_MEDIUM:0 "Mittel"
 OPTION_HIGH:0 "Hoch"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Benutzerdefiniert"
 OPTION_DEFAULT:1 "Standard"
 SETTINGS_CATEGORY_UI:0 "Benutzeroberfläche"
 SETTINGS_CATEGORY_GAME:0 "Spiel"
 SETTING_TEXTURE_QUALITY:1 "Texturqualität"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nBestimmt die Auflösung der geladenen Texturen.\n\nEine niedrigere Einstellung kann die Leistung erhöhen."
 SETTING_QUALITY:0 "Qualitätsvoreinstellung"
 SETTING_SFX:0 "SFX"
 SETTING_UI:0 "Benutzeroberfläche"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Wählt eine Voreinstellung aus den unten aufgeführten erweiterten Grafikoptionen.\n\nEine niedrige Voreinstellung verbessert die Leistung."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Aktiviert den Bloom-Effekt, der dazu führt, dass extrem helles Licht auf andere Teile des Bildes ausgeweitet wird.\n\nEine Deaktivierung kann die Leistung verbessern."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Erlaubt der Schärfentiefe, eine Kameralinse zu simulieren und Punkte außerhalb des Bilds unscharf zu machen.\n\nDas Deaktivieren kann die Leistung verbessern."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Legt fest, ob Screen Space Ambient Occlusion auf die Karte angewendet wird.\n\nDas Deaktivieren kann die Leistung verbessern."
 SETTING_REFRACTION_TOOLTIP:0 "Bestimmt, ob Spiegelungen auf dem Wasser erscheinen oder nicht."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nSteuert die Qualität der Wasserrefraktionen, falls diese aktiviert sind.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nBestimmt die höchste Qualitätsstufe von Kartenobjekten (z. B. von Gebäuden).\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nBestimmt die Detailstufe für Kartenobjekte wie Einheitenmodelle.\n\nEine niedrigere Einstellung kann die Leistung verbessern."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Wenn diese Option eingeschaltet ist, gehen 3-D-Modelle beim Heran- und Herauszoomen nahtlos zwischen verschiedenen Detailstufen (LOD) über.\n\nDas Ausschalten kann die Leistung verbessern."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Legt fest, wie Stadt- und Provinznamen auf der Karte angezeigt werden."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Bestimmt, ob nicht passierbares Gelände innerhalb der Grenzen einer Nation auf der Karte enthalten sind oder nicht."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nBestimmt die Sprache der Benutzeroberfläche."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "E-Mail Eures Paradox-Kontos"
 SETTING_FRAMERATE_CAP:1 "Frameratebegrenzung"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nBegrenzung für die Bildwiederholungsrate (Frames pro Sekunde), die das Spiel rendert.\n\nNiedrigere Einstellungen können den Stromverbrauch senken."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "Textur-Streaming"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTexturen werden nach Bedarf geladen.\n\nSenkt den Bedarf an GPU-Speicher, sorgt aber für zusätzliche CPU-Last. Kann die Leistung von GPUs mit kleinem Speicher verbessern."
 SETTING_TEXTURE_STREAMING_CACHE:0 "Textur-Streaming-Cachegröße"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Animationsgeschwindigkeit"
 SETTING_GUI_SCALING:0 "GUI-Skalierung"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Legt die Größe der gesamten Benutzeroberfläche fest. Dies ist für höhere Bildschirmauflösungen besonders nützlich.\n\n#X Ein zu hoher Wert kann dazu führen, dass Benutzeroberflächen nicht richtig auf den Bildschirm passen!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Mausschwenk"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Frei"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 Richtungen"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Deaktiviert"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nLegt fest, wie die Kamera sich verhält, wenn man mit der Maus schwenkt."
 SETTING_SCROLL_SPEED:1 "Schwenktempo"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nLegt fest, wie schnell die Karte schwenkt, wenn man Tastatur oder Maus verwendet."
 SETTING_CAMERA_ROTATION_SPEED:1 "Drehtempo der Kamera"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nDas Drehtempo der Kamera."
 SETTING_ZOOM_SPEED:1 "Zoomtempo"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nDas Zoomtempo der Kamera."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Zoomverhalten"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Relativer Zeiger"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Auf Zeiger zoomen"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Zeiger ignorieren"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nLegt fest, wie die Kamera sich relativ zum Mauszeiger beim Herein- und Herauszoomen verhält."
 SETTING_INPUT_DEVICE:0 "Eingabegerät"
 SETTING_EDITOR:0 "Editor"
 SETTING_EDITOR_POSTFIX:0 "Editor-Postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Befehl zum Öffnen des Editors"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Log-Befehl anzeigen"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Befehl zum Öffnen des Editors"
 SETTING_GRACEFUL_EXIT:0 "Kontrollierte Beendigung"
 SETTING_LANGUAGE:0 "Anzeigesprache"
 MOUSE_AND_KEYBOARD:0 "Maus & Tastatur"
 GAMEPAD:0 "Gamepad"
 SETTING_MULTISAMPLING_DISABLED:0 "Deaktiviert"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Deaktiviert"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Deaktiviert"
 # Editor
 SETTING_CAMERA_TILT:0 "Kameraneigung"
 SETTING_CAMERA_STRATEGY:0 "Kameratyp"
 SETTING_CENTERED_ZOOM_IN:0 "Zentrierter Zoom"
 SETTING_CAMERA_SPEED:0 "Kamerageschwindigkeit"
 CAMERA_TABLETOP:0 "Vogelperspektive"
 CAMERA_FPS:0 "Egoperspektive"
 CAMERA_WASD:0 "WASD-Stil"
 # Audio
 SETTING_Music:0 "Musik"
 SETTING_Ambient:0 "Umgebung"
 SETTING_Effects:0 "Effekte"
 SETTING_Master:0 "Hauptlautstärke"
 SETTING_Master_TOOLTIP:0 "#T Hauptlautstärke\n#!Steuert die Lautstärke aller Töne und Musik im Spiel."
 SETTING_Music_TOOLTIP:0 "#T Musiklautstärke\n#!Steuert die Lautstärke der Hintergrundmusik."
 SETTING_Ambient_TOOLTIP:0 "#T Umgebungslautstärke\n#!Steuert die Lautstärke der Umgebungsatmosphäre."
 SETTING_SFX_TOOLTIP:0 "#T SFX-Lautstärke\n#!Steuert die Lautstärke von Soundeffekten, z. B. im Kampf."
 SETTING_UI_TOOLTIP:0 "#T UI-Lautstärke\n#!Steuert die Lautstärke der Benutzeroberfläche."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Debug-Log-Stufe"
 SETTING_AUDIO_DEVICE_PROFILE:0 "Audioprofil"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Wählen Sie ein Audioprofil, das zu Ihrem System passt."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Lautsprecher"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Standard-Mix für $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Kopfhörer"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Ein für $SETTING_AUDIO_OPTION_HEADPHONES$ angepasster Mix."
 SETTING_AUDIO_OPTION_TV:0 "Fernseher"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Ein Mix für $SETTING_AUDIO_OPTION_TV$ und Monitorlautsprecher."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Nachtmodus"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Leiserer Ton für Spiele bei Nacht; hohe Töne werden gedämpft und die dynamische Bandbreite komprimiert."
 SETTING_MUSIC_DENSITY:0 "Musikdichte"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "Steuert das Verhältnis von Liedern, Stille und atmosphärischen Musikabschnitten\n\nIntensiv – Hauptsächlich Lieder, die nacheinander abgespielt werden, ähnlich einem Radiosender.\nAusgewogen – Die ideale Mischung aus Liedern, Stille und Atmosphäre.\nEntspannt – Hauptsächlich entspannende Musikabschnitte, die für mehr Atmosphäre bei einem mehrstündigen Spielerlebnis sorgen."
  # Game
 SETTING_AUTOSAVE:0 "Autospeicher-Intervall"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Legt fest, wie oft das Spiel automatisch gespeichert wird."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Legt fest, ob automatische Speicherstände in der Cloud gespeichert werden oder nicht."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Legt fest, ob die Kamera immer nach Norden zeigt oder nicht."
 NO_AUTOSAVE:0 "Kein Autospeichern"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED:0 "Datenübertragungstempo"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $File Transfer Speed$\n#!Legt das Maximaltempo für Speicherstandübertragungen in der Mehrspieler-Lobby fest.\n\nNiedrigere Einstellungen können die Netzwerkstabilität beim Beitritt zu Mehrspieler-Spielen verbessern, sich aber negativ auf die Mehrspieler-Ladezeiten auswirken."
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Karten-Editor-Autospeichern (Minuten)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Karten-Editor-Autospeichern-Intervall (Minuten)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Knoten-Editor-Schwenkmodus durch Ziehen"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Erleichterte Bedienung"
 SETTING_COLOR_BLIND_MODE:0 "Farbenblindheits-Modus"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Ändert die Farben, die in Spieltexten verwendet werden, damit man sie bei verschiedenen Arten von Farbenblindheit leichter erkennen kann."

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 SETTING_MOUSE_PANNING:0 "Schwenkgeschwindigkeit der Maus"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!Legt fest, ob die Karte gescrollt werden soll, wenn sich der Mauszeiger am Rand des Bildschirms oder Fensters befindet."
 SETTING_SHADOW_MAP_ENABLED:0 "Schatten"
 SETTING_SHADOW_MAP_ENABLED_TOOLTIP:0 "Aktiviert oder deaktiviert Schatten. Das Deaktivieren von Schatten führt zu einer Leistungssteigerung."
