l_turkish:
 SETTING_VALUE_WARNING:0 "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X $VALUE|%0$ değerinin üstündeki ölçeklemeler, arayüzlerin ekranın dışına taşmasına sebep olur#!"
 RECOMMENDED_GUI_SCALE:1 "$VALUE|%0$ değerinin üstündeki ölçeklemeler, arayüzlerin ekranın dışına taşmasına sebep olur"
