l_french:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Aller au-delà de $VALUE|%0$ va faire sortir les interfaces en dehors de l'écran.#!"
 RECOMMENDED_GUI_SCALE: "Aller au-delà de $VALUE|%0$ va faire sortir les interfaces en dehors de l'écran."
