l_french:
 SETTING_REFRACTION:0 "Reflets"
 SETTING_REFRACTION_QUALITY:0 "Qualité des reflets"
 SETTING_MAPOBJECT_QUALITY:0 "Objets de la carte"
 SETTING_MAP_SSAO:0 "Carte SSAO"
 SETTING_DOF:0 "Profondeur de champ"
