l_german:
 SETTING_REFRACTION:0 "Reflexion"
 SETTING_REFRACTION_QUALITY:0 "Reflexionsqualität"
 SETTING_MAPOBJECT_QUALITY:0 "Kartenobjekte"
 SETTING_MAP_SSAO:0 "Karten-SSAO"
 SETTING_DOF:0 "Schärfentiefe"
