l_braz_por:
 SETTING_REFRACTION:0 "Refração"
 SETTING_REFRACTION_QUALITY:0 "Qualidade da Refração"
 SETTING_MAPOBJECT_QUALITY:0 "Objetos do Mapa"
 SETTING_MAP_SSAO:0 "SSAO do Mapa"
 SETTING_DOF:0 "Profundidade de Campo"
