l_spanish:
 SETTING_REFRACTION:0 "Reflejos"
 SETTING_REFRACTION_QUALITY:0 "Calidad de los reflejos"
 SETTING_MAPOBJECT_QUALITY:0 "Objetos del mapa"
 SETTING_MAP_SSAO:0 "Oclusión ambiental del espacio de pantalla (SSAO) del mapa"
 SETTING_DOF:0 "Profundidad de campo"
