l_korean:
 SETTING_REFRACTION: "굴절"
 SETTING_REFRACTION_QUALITY: "굴절 품질"
 SETTING_MAPOBJECT_QUALITY: "지도 오브젝트"
 SETTING_MAP_SSAO: "지도 SSAO"
 SETTING_DOF: "피사계 심도"
 SETTING_LENS_FLARE: "렌즈 플레어"
 SETTING_SECONDARY_LENS_FLARE: "보조 렌즈 플레어"
