l_simp_chinese:
 SETTING_REFRACTION: "折射"
 SETTING_REFRACTION_QUALITY: "折射质量"
 SETTING_MAPOBJECT_QUALITY: "地图物体"
 SETTING_MAP_SSAO: "地图SSAO"
 SETTING_DOF: "景深"
 SETTING_LENS_FLARE: "镜头光斑"
 SETTING_SECONDARY_LENS_FLARE: "次要镜头光斑"
