l_russian:
 SETTING_REFRACTION:0 "Преломление"
 SETTING_REFRACTION_QUALITY:0 "Качество преломления"
 SETTING_MAPOBJECT_QUALITY:0 "Объекты на карте"
 SETTING_MAP_SSAO:0 "SSAO для карты"
 SETTING_DOF:0 "Глубина поля"
